"""Multi-tenancy foundation: organizations, users, and org_id columns.

Revision ID: 009
Revises: 008
Create Date: 2026-04-04

Background
----------
Phase 79 introduces multi-tenancy to the Conclave Engine.  All data-bearing
resources (connection, synthesis_job, webhook_registration, privacy_ledger,
privacy_transaction) must be associated with an organization so that tenant
isolation can be enforced at the application layer.

This migration:

1. Creates the ``organizations`` table (tenant root entity).
2. Creates the ``users`` table (identity anchor for JWT sub claims).
3. Seeds a default organization (UUID ``00000000-0000-0000-0000-000000000000``)
   and a default user (UUID ``00000000-0000-0000-0000-000000000001``) so that
   existing single-operator deployments continue to work in pass-through mode
   without data migration.
4. Adds ``org_id`` column (VARCHAR, initially nullable) to five tables:
   connection, synthesis_job, webhook_registration, privacy_ledger,
   privacy_transaction.
5. Backfills all existing rows to the default org UUID.
6. Alters ``org_id`` to NOT NULL on all five tables.
7. Adds foreign key constraints and indexes on ``org_id``.

Maintenance window requirement
-------------------------------
Steps 5-7 lock each table briefly for the NOT NULL constraint change.  In
production deployments with large tables (> 1 M rows), run this migration
during a scheduled maintenance window.  For PostgreSQL, ``SET lock_timeout``
and ``SET statement_timeout`` should be configured before running.

Reserved UUIDs
--------------
- Default org:  ``00000000-0000-0000-0000-000000000000``
- Default user: ``00000000-0000-0000-0000-000000000001``

These all-zeros / near-zeros UUIDs cannot be generated by ``uuid.uuid4()``
(version 4), ensuring they cannot collide with real tenant identifiers.

Downgrade note (DATA-LOSSY)
----------------------------
The down migration drops all ``org_id`` columns, drops the FK constraints,
and drops the ``users`` and ``organizations`` tables.  All tenant assignment
data is permanently lost.  **The downgrade is intentionally data-lossy** —
document this explicitly in your runbook before executing in production.

Migration rationale
-------------------
We use ``op.execute()`` with raw SQL and ``op.add_column`` / ``op.alter_column``
rather than autogenerate because autogenerate requires a live database
connection, which may not be available in an air-gapped or CI environment.

CONSTITUTION Priority 0: Security — tenant isolation foundation
CONSTITUTION Priority 4: Correctness — schema must match ORM definition
Task: P79-T79.1 — Multi-Tenancy Data Model
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# Revision identifiers used by Alembic.
revision: str = "009"
down_revision: str | None = "008"
branch_labels: str | None = None
depends_on: str | None = None

#: Default org UUID — reserved all-zeros, cannot collide with UUIDv4.
_DEFAULT_ORG_UUID: str = "00000000-0000-0000-0000-000000000000"

#: Default user UUID — reserved near-zeros, cannot collide with UUIDv4.
_DEFAULT_USER_UUID: str = "00000000-0000-0000-0000-000000000001"

#: Tables that need an ``org_id`` column added.
_ORG_ID_TABLES: list[str] = [
    "connection",
    "synthesis_job",
    "webhook_registration",
    "privacy_ledger",
    "privacy_transaction",
]


def upgrade() -> None:
    """Create organizations and users tables; add org_id to resource tables.

    Steps:
    1. Create ``organizations`` table.
    2. Create ``users`` table.
    3. Seed default organization (idempotent — INSERT ON CONFLICT DO NOTHING).
    4. Seed default user in default org (idempotent).
    5. Add nullable ``org_id`` column to each resource table.
    6. Backfill all rows to the default org UUID.
    7. Alter ``org_id`` to NOT NULL on all resource tables.
    8. Add FK constraints pointing to ``organizations.id``.
    9. Add indexes on each ``org_id`` column.
    """
    # ------------------------------------------------------------------
    # Step 1: Create organizations table
    # ------------------------------------------------------------------
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("settings", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=True,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_organizations_name", "organizations", ["name"])

    # ------------------------------------------------------------------
    # Step 2: Create users table
    # ------------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False, server_default="operator"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=True,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], name="fk_users_org_id"),
    )
    op.create_index("ix_users_org_id", "users", ["org_id"])
    op.create_index("ix_users_email", "users", ["email"])

    # ------------------------------------------------------------------
    # Step 3: Seed default organization (idempotent)
    # ------------------------------------------------------------------
    op.execute(
        f"""
        INSERT INTO organizations (id, name)
        VALUES ('{_DEFAULT_ORG_UUID}', 'Default Organization')
        ON CONFLICT (id) DO NOTHING
        """
    )

    # ------------------------------------------------------------------
    # Step 4: Seed default user in default org (idempotent)
    # ------------------------------------------------------------------
    op.execute(
        f"""
        INSERT INTO users (id, org_id, email, role)
        VALUES (
            '{_DEFAULT_USER_UUID}',
            '{_DEFAULT_ORG_UUID}',
            'default@conclave.local',
            'admin'
        )
        ON CONFLICT (id) DO NOTHING
        """
    )

    # ------------------------------------------------------------------
    # Step 5: Add nullable org_id column to each resource table
    # ------------------------------------------------------------------
    for table in _ORG_ID_TABLES:
        op.add_column(
            table,
            sa.Column("org_id", sa.String(), nullable=True),
        )

    # ------------------------------------------------------------------
    # Step 6: Backfill all existing rows to the default org UUID
    # ------------------------------------------------------------------
    for table in _ORG_ID_TABLES:
        op.execute(f"UPDATE {table} SET org_id = '{_DEFAULT_ORG_UUID}' WHERE org_id IS NULL")

    # ------------------------------------------------------------------
    # Step 7: Alter org_id to NOT NULL on all resource tables
    # NOTE: This requires all rows to have a non-NULL value (guaranteed
    # by the backfill above).  In production, this briefly locks each
    # table — schedule during a maintenance window for large deployments.
    # ------------------------------------------------------------------
    for table in _ORG_ID_TABLES:
        op.alter_column(table, "org_id", nullable=False)

    # ------------------------------------------------------------------
    # Step 8: Add FK constraints on org_id → organizations.id
    # ------------------------------------------------------------------
    for table in _ORG_ID_TABLES:
        op.create_foreign_key(
            f"fk_{table}_org_id",
            table,
            "organizations",
            ["org_id"],
            ["id"],
        )

    # ------------------------------------------------------------------
    # Step 9: Add indexes on org_id for each resource table
    # ------------------------------------------------------------------
    for table in _ORG_ID_TABLES:
        op.create_index(f"ix_{table}_org_id", table, ["org_id"])


def downgrade() -> None:
    """Drop org_id columns, FK constraints, users table, and organizations table.

    WARNING: This downgrade is DATA-LOSSY.  All tenant assignment data stored
    in org_id columns is permanently deleted.  The users and
    organizations tables and all their rows are dropped.

    Document this explicitly in your production runbook before executing.

    Resilient FK drops
    ------------------
    FK constraints are dropped with raw ALTER TABLE ... DROP CONSTRAINT IF EXISTS
    SQL rather than op.drop_constraint().  This is necessary because the
    constraints may not exist when the migration is run after create_all() +
    stamp head (the deployment pattern documented in :mod:).
    In that flow, create_all() creates the columns but not the FK constraints,
    so a plain DROP CONSTRAINT would fail with UndefinedObject.
    """
    # Drop indexes and FK constraints first (reverse order of upgrade).
    # Use IF EXISTS for FK drops so that downgrade is resilient when the schema
    # was bootstrapped via create_all() + stamp rather than via upgrade().
    for table in reversed(_ORG_ID_TABLES):
        op.drop_index(f"ix_{table}_org_id", table_name=table, if_exists=True)
        op.execute(
            f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS fk_{table}_org_id"  # nosec B608
        )
        op.drop_column(table, "org_id")

    # Drop users table (has FK to organizations).
    # Use IF EXISTS because this table is created only by the migration upgrade()
    # — it does not exist when the schema was bootstrapped via create_all() + stamp.
    op.drop_index("ix_users_email", table_name="users", if_exists=True)
    op.drop_index("ix_users_org_id", table_name="users", if_exists=True)
    op.execute("DROP TABLE IF EXISTS users")  # nosec B608

    # Drop organizations table.
    # Same rationale as users: only exists when upgrade() was run, not after stamp.
    op.drop_index("ix_organizations_name", table_name="organizations", if_exists=True)
    op.execute("DROP TABLE IF EXISTS organizations")  # nosec B608
