"""End-to-end integration tests for the full DP synthesis pipeline.

Covers the complete pipeline:
  Faker source data → DPCompatibleCTGAN with DPTrainingWrapper (via
  build_synthesis_engine / build_dp_wrapper) → sample() → StatisticalProfiler.compare()
  → ProfileDelta validation.

Also verifies that the privacy accountant ledger records a positive epsilon
after a real DP-SGD training run.

Acceptance Criteria (verbatim from P7-T7.5 spec):
  AC1: E2E integration test covering the full DP synthesis pipeline:
       Load source data → train with DP-CTGAN → generate synthetic rows
       → ProfileDelta comparison.
  AC2: Privacy accountant ledger test: verify spend_budget() deducts the
       correct epsilon amount after a real DP training run.

No PII is used.  All fixture data is generated by Faker.

These tests require the synthesizer dependency group:
  poetry install --with synthesizer

Run with:
  poetry run pytest tests/integration/test_e2e_dp_synthesis.py -v --no-cov

Task: P7-T7.5 — Phase 7 E2E Test & Retrospective
"""

from __future__ import annotations

import math
import tempfile
import warnings
from collections.abc import Generator
from pathlib import Path

import pandas as pd
import pytest
from faker import Faker

# ---------------------------------------------------------------------------
# Mark all tests in this module as integration + synthesizer tests
# ADV-069: route via `pytest -m synthesizer` in CI (see P8-T8.4).
# ---------------------------------------------------------------------------
pytestmark = [pytest.mark.integration, pytest.mark.synthesizer]


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def persons_df() -> pd.DataFrame:
    """Generate a 120-row fictional persons DataFrame for E2E DP training.

    All data is Faker-generated — no real PII.  Uses a fixed seed for
    deterministic behaviour across test runs.

    Returns:
        DataFrame with columns: id (int), age (int), salary (int), dept (str).
    """
    fake = Faker()
    Faker.seed(99999)

    rows = [
        {
            "id": i,
            "age": fake.random_int(min=18, max=80),
            "salary": fake.random_int(min=30000, max=150000),
            "dept": fake.random_element(["Engineering", "Marketing", "Sales", "HR"]),
        }
        for i in range(1, 121)
    ]
    return pd.DataFrame(rows)


@pytest.fixture
def persons_parquet(persons_df: pd.DataFrame) -> Generator[str]:
    """Write persons_df to a temporary Parquet file.

    Returns:
        Absolute path to the Parquet file.  The TemporaryDirectory is managed
        for the lifetime of the test.
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        path = str(Path(tmpdir) / "persons.parquet")
        persons_df.to_parquet(path, index=False, engine="pyarrow")
        yield path


# ---------------------------------------------------------------------------
# AC1: Full DP synthesis pipeline E2E
# ---------------------------------------------------------------------------


class TestE2EDPSynthesisPipeline:
    """AC1: Full E2E pipeline — Faker → DP-CTGAN → sample → ProfileDelta."""

    def test_e2e_dp_synthesis_produces_dataframe(
        self, persons_parquet: str, persons_df: pd.DataFrame
    ) -> None:
        """E2E: DP synthesis pipeline produces a non-empty DataFrame.

        Trains SynthesisEngine with build_dp_wrapper(), generates synthetic
        rows via the trained model's sample(), and verifies the output is a
        non-empty DataFrame with the expected schema.

        This is the primary E2E integration test for T7.5 AC1.

        The model type check uses duck-typing (hasattr) rather than isinstance
        to avoid importing internal synthesizer classes past the bootstrapper
        boundary.
        """
        from synth_engine.bootstrapper.main import build_dp_wrapper, build_synthesis_engine

        wrapper = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=1.1)
        engine = build_synthesis_engine(epochs=2)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            artifact = engine.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper,
            )

        # Duck-type check: the model must expose a callable sample() method.
        # We avoid importing DPCompatibleCTGAN to respect the bootstrapper
        # boundary — internal synthesizer classes are not part of the public API.
        assert hasattr(artifact.model, "sample"), (
            "artifact.model must have a 'sample' attribute when dp_wrapper is provided"
        )
        assert callable(artifact.model.sample), (
            "artifact.model.sample must be callable when dp_wrapper is provided"
        )

        # Generate synthetic rows via sample()
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            synthetic_df = artifact.model.sample(num_rows=50)

        assert isinstance(synthetic_df, pd.DataFrame), (
            f"sample() must return pd.DataFrame, got {type(synthetic_df)}"
        )
        assert len(synthetic_df) == 50, f"Expected 50 synthetic rows, got {len(synthetic_df)}"

    def test_e2e_dp_synthesis_schema_matches_source(
        self, persons_parquet: str, persons_df: pd.DataFrame
    ) -> None:
        """E2E: Synthetic output schema matches source DataFrame column set.

        Per Known Failure Pattern: return-value assertions must check schema
        (column names) AND content (row count).  This test covers schema.
        """
        from synth_engine.bootstrapper.main import build_dp_wrapper, build_synthesis_engine

        wrapper = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=1.1)
        engine = build_synthesis_engine(epochs=2)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            artifact = engine.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper,
            )

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            synthetic_df = artifact.model.sample(num_rows=60)

        assert set(synthetic_df.columns) == set(persons_df.columns), (
            f"Column mismatch: expected {set(persons_df.columns)}, got {set(synthetic_df.columns)}"
        )

    def test_e2e_dp_synthesis_no_all_nan_columns(
        self, persons_parquet: str, persons_df: pd.DataFrame
    ) -> None:
        """E2E: No column in synthetic output should be entirely NaN.

        Per Known Failure Pattern: return-value assertions check content.
        Guards against a silent reverse_transform failure producing an all-NaN column.
        """
        from synth_engine.bootstrapper.main import build_dp_wrapper, build_synthesis_engine

        wrapper = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=1.1)
        engine = build_synthesis_engine(epochs=2)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            artifact = engine.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper,
            )

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            synthetic_df = artifact.model.sample(num_rows=40)

        for col in synthetic_df.columns:
            all_nan = synthetic_df[col].isna().all()
            assert not all_nan, (
                f"Column '{col}' is entirely NaN in E2E DP synthesis output — "
                "this suggests a reverse_transform failure."
            )

    def test_e2e_dp_synthesis_profile_delta_comparison(
        self, persons_parquet: str, persons_df: pd.DataFrame
    ) -> None:
        """E2E: ProfileDelta comparison succeeds after DP synthesis.

        Trains DPCompatibleCTGAN, generates 100 synthetic rows, profiles both
        source and synthetic DataFrames, and verifies ProfileDelta is produced
        with entries for numeric columns.

        This is the StatisticalProfiler integration arm of AC1.
        """
        from synth_engine.bootstrapper.main import build_dp_wrapper, build_synthesis_engine
        from synth_engine.modules.profiler.models import ProfileDelta
        from synth_engine.modules.profiler.profiler import StatisticalProfiler

        wrapper = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=1.1)
        engine = build_synthesis_engine(epochs=2)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            artifact = engine.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper,
            )

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            synthetic_df = artifact.model.sample(num_rows=100)

        # Profile both DataFrames
        profiler = StatisticalProfiler()
        baseline_profile = profiler.profile("persons_baseline", persons_df)
        synthetic_profile = profiler.profile("persons_synthetic", synthetic_df)
        delta = profiler.compare(baseline=baseline_profile, synthetic=synthetic_profile)

        assert isinstance(delta, ProfileDelta), (
            f"profiler.compare() must return a ProfileDelta, got {type(delta)}"
        )

        # Verify entries exist for numeric columns
        numeric_columns = ["age", "salary"]
        for col in numeric_columns:
            assert col in delta.column_deltas, (
                f"Expected column '{col}' in ProfileDelta.column_deltas, "
                f"got {list(delta.column_deltas.keys())}"
            )
            col_delta = delta.column_deltas[col]
            assert col_delta.mean_drift is not None, (
                f"Column '{col}': mean_drift must not be None for numeric columns "
                "with valid data in both source and synthetic profiles."
            )

    def test_e2e_dp_synthesis_epsilon_positive_after_pipeline(self, persons_parquet: str) -> None:
        """E2E: epsilon_spent > 0 after the complete DP synthesis pipeline.

        After the full pipeline (train → sample), the DPTrainingWrapper must
        report a positive, finite epsilon — confirming Opacus was actually
        activated during training.
        """
        from synth_engine.bootstrapper.main import build_dp_wrapper, build_synthesis_engine

        wrapper = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=1.1)
        engine = build_synthesis_engine(epochs=2)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            artifact = engine.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper,
            )

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            _synthetic_df = artifact.model.sample(num_rows=50)

        epsilon = wrapper.epsilon_spent(delta=1e-5)

        assert epsilon > 0.0, (
            f"epsilon_spent(delta=1e-5) must be > 0 after full DP pipeline, got {epsilon}. "
            "Opacus PrivacyEngine must have been activated during SynthesisEngine.train()."
        )
        assert math.isfinite(epsilon), (
            f"epsilon_spent must be finite after DP pipeline, got {epsilon}."
        )


# ---------------------------------------------------------------------------
# AC1 (FK post-processing arm): Apply FK post-processing to synthetic output
# ---------------------------------------------------------------------------


class TestE2EFKPostProcessing:
    """AC1 (FK arm): FK post-processing produces a valid child synthetic table."""

    def test_fk_post_processing_eliminates_orphans(
        self, persons_parquet: str, persons_df: pd.DataFrame
    ) -> None:
        """FK post-processing replaces orphan FK values with valid parent PKs.

        Generates a synthetic table, then verifies that apply_fk_post_processing()
        correctly replaces all values outside ``valid_pks`` with valid ones.

        This completes the FK post-processing arm of the E2E pipeline:
        DP-CTGAN train → sample → apply_fk_post_processing → zero orphan FKs.
        """
        from synth_engine.bootstrapper.main import build_dp_wrapper, build_synthesis_engine
        from synth_engine.modules.synthesizer.training.engine import apply_fk_post_processing

        wrapper = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=1.1)
        engine = build_synthesis_engine(epochs=2)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            artifact = engine.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper,
            )

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            synthetic_df = artifact.model.sample(num_rows=50)

        # Use a known set of valid parent PKs (first 30 IDs from the source fixture)
        valid_pks = set(range(1, 31))

        # Apply FK post-processing on the 'id' column to simulate FK patching.
        result = apply_fk_post_processing(
            child_df=synthetic_df,
            fk_column="id",
            valid_parent_pks=valid_pks,
            rng_seed=42,
        )

        # All id values in the result must now be in valid_pks
        orphan_count = (~result["id"].isin(valid_pks)).sum()
        assert orphan_count == 0, (
            f"apply_fk_post_processing() must eliminate all orphan FK values, "
            f"found {orphan_count} orphans after post-processing."
        )
        # Row count must be preserved
        assert len(result) == len(synthetic_df), (
            f"Row count must be preserved: expected {len(synthetic_df)}, got {len(result)}"
        )


# ---------------------------------------------------------------------------
# AC2: Privacy accountant ledger test
# ---------------------------------------------------------------------------


class TestPrivacyAccountantLedger:
    """AC2: Verify privacy accountant spend_budget() deducts epsilon after DP training."""

    @pytest.mark.asyncio
    async def test_spend_budget_deducts_epsilon_after_real_training(
        self, persons_parquet: str
    ) -> None:
        """AC2: spend_budget() atomically deducts epsilon from a PrivacyLedger.

        This test exercises the full accountant integration:
          1. Train DPCompatibleCTGAN with DPTrainingWrapper (real Opacus run).
          2. Read epsilon_spent from the wrapper.
          3. Call spend_budget() with the actual epsilon spent.
          4. Verify the ledger's total_spent_epsilon was incremented by exactly
             the amount passed.

        Uses an in-memory SQLite database via the shared get_async_engine /
        get_async_session helpers — matches the session type that accountant.py
        expects (sqlalchemy.ext.asyncio.AsyncSession, not SQLModel's wrapper)
        to avoid DeprecationWarning from SQLModel's session.execute() override.
        """
        from sqlalchemy import select
        from sqlalchemy.ext.asyncio import AsyncSession
        from sqlmodel import SQLModel

        from synth_engine.bootstrapper.main import build_dp_wrapper, build_synthesis_engine
        from synth_engine.modules.privacy.accountant import spend_budget
        from synth_engine.modules.privacy.ledger import PrivacyLedger
        from synth_engine.shared.db import get_async_engine

        wrapper = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=1.1)
        engine_synth = build_synthesis_engine(epochs=2)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            engine_synth.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper,
            )

        epsilon_from_wrapper = wrapper.epsilon_spent(delta=1e-5)

        assert epsilon_from_wrapper > 0.0, (
            f"Precondition: epsilon_spent must be > 0 after DP training, got {epsilon_from_wrapper}"
        )
        assert math.isfinite(epsilon_from_wrapper), (
            f"Precondition: epsilon_spent must be finite, got {epsilon_from_wrapper}"
        )

        db_engine = get_async_engine("sqlite+aiosqlite:///:memory:")
        async with db_engine.begin() as conn:
            await conn.run_sync(SQLModel.metadata.create_all)

        # Seed a PrivacyLedger row with plenty of budget.
        # Use plain SQLAlchemy AsyncSession (not SQLModel's wrapper) so that
        # accountant.py's session.execute() call does not raise a
        # DeprecationWarning.  Use commit() + refresh() to get the
        # auto-generated id — avoids MissingGreenlet on expired instances.
        allocated = epsilon_from_wrapper * 10.0
        async with AsyncSession(db_engine, expire_on_commit=False) as session:
            ledger = PrivacyLedger(
                total_allocated_epsilon=allocated,
                total_spent_epsilon=0.0,
            )
            session.add(ledger)
            await session.commit()
            await session.refresh(ledger)
            ledger_id = ledger.id

        # Spend the epsilon via the accountant
        async with AsyncSession(db_engine, expire_on_commit=False) as session:
            await spend_budget(
                amount=epsilon_from_wrapper,
                job_id=1,
                ledger_id=ledger_id,
                session=session,
                note="E2E DP test — P7-T7.5",
            )

        # Read back the ledger to verify deduction
        async with AsyncSession(db_engine, expire_on_commit=False) as session:
            result = await session.execute(
                select(PrivacyLedger).where(
                    PrivacyLedger.id == ledger_id  # type: ignore[arg-type]
                )
            )
            updated_ledger = result.scalar_one()
            total_spent = float(updated_ledger.total_spent_epsilon)

        # The ledger's total_spent_epsilon must equal the epsilon we spent
        assert abs(total_spent - epsilon_from_wrapper) < 1e-9, (
            f"spend_budget() must deduct exactly epsilon={epsilon_from_wrapper:.6f} "
            f"from the ledger; ledger shows total_spent={total_spent:.6f} "
            f"(delta={abs(total_spent - epsilon_from_wrapper):.2e})"
        )

    @pytest.mark.asyncio
    async def test_spend_budget_raises_on_budget_exhaustion(self, persons_parquet: str) -> None:
        """AC2: spend_budget() raises BudgetExhaustionError when budget is exhausted.

        Trains with DP, then attempts to spend more epsilon than the ledger
        allows.  Verifies that BudgetExhaustionError propagates correctly
        from the accountant layer.

        Uses plain SQLAlchemy AsyncSession (not SQLModel's wrapper) to avoid
        DeprecationWarning from SQLModel's session.execute() override.
        """
        from sqlalchemy.ext.asyncio import AsyncSession
        from sqlmodel import SQLModel

        from synth_engine.bootstrapper.main import build_dp_wrapper, build_synthesis_engine
        from synth_engine.modules.privacy.accountant import spend_budget
        from synth_engine.modules.privacy.dp_engine import BudgetExhaustionError
        from synth_engine.modules.privacy.ledger import PrivacyLedger
        from synth_engine.shared.db import get_async_engine

        wrapper = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=1.1)
        engine_synth = build_synthesis_engine(epochs=2)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            engine_synth.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper,
            )

        epsilon_from_wrapper = wrapper.epsilon_spent(delta=1e-5)
        assert epsilon_from_wrapper > 0.0, "Precondition: must have spent some epsilon."

        db_engine = get_async_engine("sqlite+aiosqlite:///:memory:")
        async with db_engine.begin() as conn:
            await conn.run_sync(SQLModel.metadata.create_all)

        # Seed a ledger with an absurdly small budget — guaranteed to be exceeded.
        # Use commit() + refresh() to retrieve the auto-generated id.
        async with AsyncSession(db_engine, expire_on_commit=False) as session:
            ledger = PrivacyLedger(
                total_allocated_epsilon=1e-10,
                total_spent_epsilon=0.0,
            )
            session.add(ledger)
            await session.commit()
            await session.refresh(ledger)
            ledger_id = ledger.id

        # Attempt to spend epsilon_from_wrapper — this must exceed 1e-10
        with pytest.raises(BudgetExhaustionError):
            async with AsyncSession(db_engine, expire_on_commit=False) as session:
                await spend_budget(
                    amount=epsilon_from_wrapper,
                    job_id=2,
                    ledger_id=ledger_id,
                    session=session,
                )

    def test_epsilon_wrapper_value_is_positive_and_finite(self, persons_parquet: str) -> None:
        """AC2 (wrapper): epsilon_spent() is positive and finite after real DP training.

        Separate guard to verify the DPTrainingWrapper reports a reasonable
        epsilon value.  A non-positive or non-finite value would indicate
        Opacus failed to run real gradient steps.
        """
        from synth_engine.bootstrapper.main import build_dp_wrapper, build_synthesis_engine

        wrapper = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=1.1)
        engine = build_synthesis_engine(epochs=2)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            engine.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper,
            )

        epsilon = wrapper.epsilon_spent(delta=1e-5)

        assert isinstance(epsilon, float), f"epsilon_spent() must return float, got {type(epsilon)}"
        assert epsilon > 0.0, f"epsilon_spent() must be > 0 after real DP training, got {epsilon}"
        assert math.isfinite(epsilon), f"epsilon_spent() must be finite, got {epsilon}"
