"""Integration tests for SynthesisEngine using a real CTGAN model.

These tests exercise the full synthesis pipeline:
  1. Train a CTGAN model on a Faker-generated 100-row persons DataFrame.
  2. Generate 50 synthetic rows and verify the output schema matches the
     source schema exactly (column names and dtypes).
  3. Verify that the synthesizer module does NOT import from modules/ingestion/,
     modules/masking/, or modules/subsetting/ (import boundary enforcement).

No real PII is used.  All fixture data is generated by Faker.

Task: P4-T4.2b — Synthesizer Core (SDV/CTGAN Integration)
ADR: ADR-0017 (CTGAN + Opacus; per-table training with FK post-processing)
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import pandas as pd
import pytest
from faker import Faker


@pytest.fixture
def persons_parquet(tmp_path: Path) -> str:
    """Generate a 100-row fictional persons Parquet fixture.

    All data is Faker-generated — no real PII.

    Args:
        tmp_path: pytest-provided temporary directory.

    Returns:
        Absolute path to the written Parquet file.
    """
    fake = Faker()
    Faker.seed(12345)

    rows = [
        {
            "id": i,
            "name": fake.name(),
            "age": fake.random_int(min=18, max=80),
            "salary": fake.random_int(min=30000, max=150000),
            "department": fake.random_element(["Engineering", "Marketing", "Sales", "HR"]),
        }
        for i in range(1, 101)
    ]
    df = pd.DataFrame(rows)
    parquet_path = str(tmp_path / "persons.parquet")
    df.to_parquet(parquet_path, index=False, engine="pyarrow")
    return parquet_path


class TestSynthesisEngineCTGANIntegration:
    """Integration tests: real CTGAN training on Faker-generated data."""

    def test_train_returns_model_artifact(self, persons_parquet: str) -> None:
        """train() with real CTGAN must return a ModelArtifact."""
        from synth_engine.modules.synthesizer.engine import SynthesisEngine
        from synth_engine.modules.synthesizer.models import ModelArtifact

        engine = SynthesisEngine(epochs=2)
        result = engine.train(table_name="persons", parquet_path=persons_parquet)
        assert isinstance(result, ModelArtifact)

    def test_generated_schema_matches_source_column_names(
        self, persons_parquet: str
    ) -> None:
        """Generated output column names must exactly match the source schema."""
        from synth_engine.modules.synthesizer.engine import SynthesisEngine

        source_df = pd.read_parquet(persons_parquet, engine="pyarrow")
        engine = SynthesisEngine(epochs=2)
        artifact = engine.train(table_name="persons", parquet_path=persons_parquet)
        synthetic_df = engine.generate(artifact=artifact, n_rows=50)

        assert set(synthetic_df.columns) == set(source_df.columns)

    def test_generated_schema_matches_source_dtypes(
        self, persons_parquet: str
    ) -> None:
        """Generated output dtypes must exactly match the source dtypes."""
        from synth_engine.modules.synthesizer.engine import SynthesisEngine

        source_df = pd.read_parquet(persons_parquet, engine="pyarrow")
        engine = SynthesisEngine(epochs=2)
        artifact = engine.train(table_name="persons", parquet_path=persons_parquet)
        synthetic_df = engine.generate(artifact=artifact, n_rows=50)

        for col in source_df.columns:
            assert synthetic_df[col].dtype == source_df[col].dtype, (
                f"Column '{col}' dtype mismatch: "
                f"expected {source_df[col].dtype}, got {synthetic_df[col].dtype}"
            )

    def test_generated_row_count_matches_request(self, persons_parquet: str) -> None:
        """generate() must return exactly the requested number of rows."""
        from synth_engine.modules.synthesizer.engine import SynthesisEngine

        engine = SynthesisEngine(epochs=2)
        artifact = engine.train(table_name="persons", parquet_path=persons_parquet)
        synthetic_df = engine.generate(artifact=artifact, n_rows=50)

        assert len(synthetic_df) == 50

    def test_artifact_save_load_round_trip(self, persons_parquet: str) -> None:
        """ModelArtifact.save() + load() must preserve a usable model.

        After round-trip, generate() must still produce a valid DataFrame.
        """
        from synth_engine.modules.synthesizer.engine import SynthesisEngine
        from synth_engine.modules.synthesizer.models import ModelArtifact

        with tempfile.TemporaryDirectory() as tmpdir:
            engine = SynthesisEngine(epochs=2)
            artifact = engine.train(table_name="persons", parquet_path=persons_parquet)

            save_path = str(Path(tmpdir) / "persons_artifact.pkl")
            returned_path = artifact.save(save_path)
            assert returned_path == save_path

            loaded_artifact = ModelArtifact.load(save_path)
            assert isinstance(loaded_artifact, ModelArtifact)

            # Model must still be functional after round-trip
            result = engine.generate(artifact=loaded_artifact, n_rows=20)
            assert isinstance(result, pd.DataFrame)
            assert len(result) == 20


class TestImportBoundaryEnforcement:
    """Verify that synthesizer does NOT import from forbidden modules.

    Per Context & Constraints: 'The module must not import from
    modules/ingestion/, modules/masking/, or modules/subsetting/.'

    This test confirms via import-linter that the contract holds.
    """

    def test_synthesizer_does_not_import_from_ingestion(self) -> None:
        """import-linter must confirm synthesizer has no ingestion dependency."""
        import subprocess
        import sys

        result = subprocess.run(  # noqa: S603
            [sys.executable, "-m", "importlinter"],
            capture_output=True,
            text=True,
        )
        # importlinter exits 0 on success, non-zero on contract violation
        assert result.returncode == 0, (
            f"import-linter found contract violations:\n{result.stdout}\n{result.stderr}"
        )
