"""Integration tests for SynthesisEngine using a real CTGAN model.

These tests exercise the full synthesis pipeline:
  1. Train a CTGAN model on a Faker-generated 100-row persons DataFrame.
  2. Generate 50 synthetic rows and verify the output schema matches the
     source schema exactly (column names, dtypes, and nullable flags).
  3. Verify that the synthesizer module does NOT import from modules/ingestion/,
     modules/masking/, or modules/subsetting/ (import boundary enforcement).
  4. (T4.2c) Integration test for run_synthesis_job using a real PostgreSQL
     database: assert status == "COMPLETE" and artifact_path is set.

No real PII is used.  All fixture data is generated by Faker.

Task: P4-T4.2b — Synthesizer Core (SDV/CTGAN Integration)
Task: P4-T4.2c — Huey Task Wiring & Checkpointing (PostgreSQL integration test)
ADR: ADR-0017 (CTGAN + Opacus; per-table training with FK post-processing)
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path

import pandas as pd
import pytest
from faker import Faker
from pytest_postgresql import factories

from tests.conftest_types import PostgreSQLProc

pytestmark = [pytest.mark.integration, pytest.mark.synthesizer]  # ADV-073


@pytest.fixture
def persons_parquet(tmp_path: Path) -> str:
    """Generate a 100-row fictional persons Parquet fixture.

    All data is Faker-generated — no real PII.

    Args:
        tmp_path: pytest-provided temporary directory.

    Returns:
        Absolute path to the written Parquet file.
    """
    fake = Faker()
    Faker.seed(12345)

    rows = [
        {
            "id": i,
            "name": fake.name(),
            "age": fake.random_int(min=18, max=80),
            "salary": fake.random_int(min=30000, max=150000),
            "department": fake.random_element(["Engineering", "Marketing", "Sales", "HR"]),
        }
        for i in range(1, 101)
    ]
    df = pd.DataFrame(rows)
    parquet_path = str(tmp_path / "persons.parquet")
    df.to_parquet(parquet_path, index=False, engine="pyarrow")
    return parquet_path


@pytest.fixture
def persons_parquet_with_nulls(tmp_path: Path) -> str:
    """Generate a 100-row persons Parquet fixture with nulls in one column.

    The ``opt_field`` column has ~30% null values so that the nullable flag
    test can assert True for that column.  All data is fictional.

    Args:
        tmp_path: pytest-provided temporary directory.

    Returns:
        Absolute path to the written Parquet file.
    """
    import numpy as np

    rng = np.random.default_rng(99)
    ids = list(range(1, 101))
    ages = rng.integers(18, 80, size=100).tolist()
    # ~30% nulls in opt_field
    opt_values: list[float | None] = [
        None if rng.random() < 0.3 else float(rng.integers(100, 999)) for _ in range(100)
    ]

    df = pd.DataFrame({"id": ids, "age": ages, "opt_field": opt_values})
    parquet_path = str(tmp_path / "persons_with_nulls.parquet")
    df.to_parquet(parquet_path, index=False, engine="pyarrow")
    return parquet_path


class TestSynthesisEngineCTGANIntegration:
    """Integration tests: real CTGAN training on Faker-generated data."""

    def test_train_returns_model_artifact(self, persons_parquet: str) -> None:
        """train() with real CTGAN must return a ModelArtifact."""
        from synth_engine.modules.synthesizer.storage.artifact import ModelArtifact
        from synth_engine.modules.synthesizer.training.engine import SynthesisEngine

        engine = SynthesisEngine(epochs=2)
        result = engine.train(table_name="persons", parquet_path=persons_parquet)
        assert isinstance(result, ModelArtifact)

    def test_generated_schema_matches_source_column_names(self, persons_parquet: str) -> None:
        """Generated output column names must exactly match the source schema."""
        from synth_engine.modules.synthesizer.training.engine import SynthesisEngine

        source_df = pd.read_parquet(persons_parquet, engine="pyarrow")
        engine = SynthesisEngine(epochs=2)
        artifact = engine.train(table_name="persons", parquet_path=persons_parquet)
        synthetic_df = engine.generate(artifact=artifact, n_rows=50)

        assert set(synthetic_df.columns) == set(source_df.columns)

    def test_generated_schema_matches_source_dtypes(self, persons_parquet: str) -> None:
        """Generated output dtypes must exactly match the source dtypes."""
        from synth_engine.modules.synthesizer.training.engine import SynthesisEngine

        source_df = pd.read_parquet(persons_parquet, engine="pyarrow")
        engine = SynthesisEngine(epochs=2)
        artifact = engine.train(table_name="persons", parquet_path=persons_parquet)
        synthetic_df = engine.generate(artifact=artifact, n_rows=50)

        for col in source_df.columns:
            assert synthetic_df[col].dtype == source_df[col].dtype, (
                f"Column '{col}' dtype mismatch: "
                f"expected {source_df[col].dtype}, got {synthetic_df[col].dtype}"
            )

    def test_generated_row_count_matches_request(self, persons_parquet: str) -> None:
        """generate() must return exactly the requested number of rows."""
        from synth_engine.modules.synthesizer.training.engine import SynthesisEngine

        engine = SynthesisEngine(epochs=2)
        artifact = engine.train(table_name="persons", parquet_path=persons_parquet)
        synthetic_df = engine.generate(artifact=artifact, n_rows=50)

        assert len(synthetic_df) == 50

    def test_artifact_save_load_round_trip(self, persons_parquet: str) -> None:
        """ModelArtifact.save() + load() must preserve a usable model.

        After round-trip, generate() must still produce a valid DataFrame.
        """
        from synth_engine.modules.synthesizer.storage.artifact import ModelArtifact
        from synth_engine.modules.synthesizer.training.engine import SynthesisEngine

        with tempfile.TemporaryDirectory() as tmpdir:
            engine = SynthesisEngine(epochs=2)
            artifact = engine.train(table_name="persons", parquet_path=persons_parquet)

            save_path = str(Path(tmpdir) / "persons_artifact.pkl")
            returned_path = artifact.save(save_path)
            assert returned_path == save_path

            loaded_artifact = ModelArtifact.load(save_path)
            assert isinstance(loaded_artifact, ModelArtifact)

            # Model must still be functional after round-trip
            result = engine.generate(artifact=loaded_artifact, n_rows=20)
            assert isinstance(result, pd.DataFrame)
            assert len(result) == 20

    def test_artifact_nullable_flags_match_source(self, persons_parquet_with_nulls: str) -> None:
        """Artifact column_nullables must reflect actual null presence in source data.

        ``id`` and ``age`` have no nulls → nullable flag must be False.
        ``opt_field`` has ~30% nulls → nullable flag must be True.
        """
        from synth_engine.modules.synthesizer.training.engine import SynthesisEngine

        source_df = pd.read_parquet(persons_parquet_with_nulls, engine="pyarrow")
        engine = SynthesisEngine(epochs=2)
        artifact = engine.train(
            table_name="persons_with_nulls",
            parquet_path=persons_parquet_with_nulls,
        )

        # Verify nullable flags match actual null presence in source
        for col in source_df.columns:
            expected_nullable = bool(source_df[col].isnull().any())
            assert artifact.column_nullables[col] == expected_nullable, (
                f"Column '{col}' nullable flag mismatch: "
                f"expected {expected_nullable}, got {artifact.column_nullables[col]}"
            )

        # Explicit checks: id and age have no nulls; opt_field does
        assert artifact.column_nullables["id"] is False
        assert artifact.column_nullables["age"] is False
        assert artifact.column_nullables["opt_field"] is True


class TestImportBoundaryEnforcement:
    """Verify that synthesizer does NOT import from forbidden modules.

    Per Context & Constraints: 'The module must not import from
    modules/ingestion/, modules/masking/, or modules/subsetting/.'

    This test confirms via import-linter that the contract holds.
    """

    def test_synthesizer_does_not_import_from_ingestion(self) -> None:
        """import-linter must confirm synthesizer has no ingestion dependency.

        Uses the ``lint-imports`` CLI entry point installed by the
        import-linter package (not ``python -m importlinter`` which is
        not a valid entry point for this package).
        """
        lint_imports = shutil.which("lint-imports")
        if lint_imports is None:
            pytest.skip("lint-imports binary not found — import-linter not installed")

        result = subprocess.run(
            [lint_imports],
            capture_output=True,
            text=True,
        )
        # lint-imports exits 0 on success, non-zero on contract violation
        assert result.returncode == 0, (
            f"import-linter found contract violations:\n{result.stdout}\n{result.stderr}"
        )


# ---------------------------------------------------------------------------
# pytest-postgresql process fixture for T4.2c integration test
# ---------------------------------------------------------------------------

synth_pg_proc = factories.postgresql_proc(port=None)  # port=None picks a free port


class TestSynthesisJobTaskIntegration:
    """Integration tests for _run_synthesis_job_impl with a real PostgreSQL database.

    These tests verify the full status lifecycle (QUEUED → TRAINING → COMPLETE)
    against a real PostgreSQL instance provisioned by pytest-postgresql.
    SynthesisEngine.train() is mocked so the tests do not require sdv/torch.

    Task: P4-T4.2c — Huey Task Wiring & Checkpointing
    """

    def test_synthesis_job_complete_with_real_db(
        self,
        tmp_path: Path,
        synth_pg_proc: PostgreSQLProc,
    ) -> None:
        """_run_synthesis_job_impl must reach COMPLETE status using a real PostgreSQL DB.

        Verifies end-to-end lifecycle:
          1. A SynthesisJob row is inserted with status=QUEUED.
          2. _run_synthesis_job_impl is called with a mocked SynthesisEngine.
          3. The final DB record has status=COMPLETE and artifact_path set.

        Uses pytest-postgresql to provision an ephemeral PostgreSQL instance.
        SynthesisEngine.train() is mocked to avoid requiring sdv/torch.

        Args:
            tmp_path: pytest temporary directory for parquet and checkpoint files.
            synth_pg_proc: pytest-postgresql process executor fixture.
        """
        from unittest.mock import MagicMock, patch

        import psycopg2
        from sqlmodel import Session, SQLModel, create_engine

        from synth_engine.modules.synthesizer.jobs.job_models import SynthesisJob
        from synth_engine.modules.synthesizer.jobs.job_orchestration import _run_synthesis_job_impl

        # Build the SQLAlchemy URL from the running proc fixture.
        proc = synth_pg_proc
        dbname = "synth_test_db"

        # Create the test database (the proc fixture starts PostgreSQL but does
        # not pre-create a named database; we connect to postgres to create it).
        admin_conn = psycopg2.connect(
            dbname="postgres",
            user=proc.user,
            host=proc.host,
            port=proc.port,
            password=proc.password or "",
        )
        admin_conn.autocommit = True
        with admin_conn.cursor() as cur:
            cur.execute(f"CREATE DATABASE {dbname}")
        admin_conn.close()

        pg_url = (
            f"postgresql+psycopg2://{proc.user}:{proc.password or ''}"
            f"@{proc.host}:{proc.port}/{dbname}"
        )
        db_engine = create_engine(pg_url)
        SQLModel.metadata.create_all(db_engine)

        # Dummy parquet path — check_memory_feasibility is mocked, so the
        # file does not need to exist.  _get_parquet_dimensions falls back
        # to conservative defaults when pyarrow is absent or file missing.
        parquet_path = str(tmp_path / "test_table.parquet")

        checkpoint_dir = str(tmp_path / "checkpoints")
        Path(checkpoint_dir).mkdir()

        # Insert a QUEUED job.
        with Session(db_engine) as session:
            job = SynthesisJob(
                status="QUEUED",
                total_epochs=3,
                num_rows=100,
                checkpoint_every_n=5,
                table_name="test_table",
                parquet_path=parquet_path,
            )
            session.add(job)
            session.commit()
            session.refresh(job)
            assert job.id is not None
            job_id: int = job.id

        # Mock SynthesisEngine to avoid requiring sdv/torch.
        mock_engine = MagicMock()
        mock_artifact = MagicMock()
        mock_engine.train.return_value = mock_artifact
        mock_artifact.save.return_value = str(
            tmp_path / "checkpoints" / f"job_{job_id}_epoch_3.pkl"
        )
        with Session(db_engine) as session:
            with patch(
                "synth_engine.modules.synthesizer.jobs.job_orchestration.check_memory_feasibility"
            ):
                _run_synthesis_job_impl(
                    job_id=job_id,
                    session=session,
                    engine=mock_engine,
                    checkpoint_dir=checkpoint_dir,
                )

        # Verify final DB state in a fresh session.
        with Session(db_engine) as session:
            final_job = session.get(SynthesisJob, job_id)
            assert final_job is not None
            assert final_job.status == "COMPLETE", (
                f"Expected status=COMPLETE, got {final_job.status!r} "
                f"(error_msg={final_job.error_msg!r})"
            )
            assert final_job.artifact_path is not None, (
                "Expected artifact_path to be set after COMPLETE"
            )
