"""Integration tests for Opacus DP-SGD end-to-end wiring.

Verifies the full wiring chain:
  bootstrapper.build_dp_wrapper() → SynthesisEngine.train(dp_wrapper=...) →
  DPCompatibleCTGAN.fit() → DPTrainingWrapper.wrap() → Opacus PrivacyEngine

Acceptance Criteria (verbatim from P7-T7.3 spec):
  AC4: Integration test: train with DP-SGD enabled, verify
       wrapper.epsilon_spent(delta=1e-5) > 0 after training completes.
  AC5: Integration test: budget exhaustion — set allocated_epsilon low enough
       that check_budget() raises BudgetExhaustionError mid-training.
  AC6: Integration test: verify PrivacyEngine.get_epsilon(delta) returns a
       value consistent with the training configuration.

No PII is used.  All fixture data is generated by Faker.

These tests require the synthesizer dependency group:
  poetry install --with synthesizer

Run with:
  poetry run pytest tests/integration/test_dp_wiring_integration.py -v --no-cov

Task: P7-T7.3 — Opacus End-to-End Wiring
ADV-048 drain.
"""

from __future__ import annotations

import tempfile
import warnings
from pathlib import Path

import pandas as pd
import pytest
from faker import Faker

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def persons_df() -> pd.DataFrame:
    """Generate a 100-row fictional persons DataFrame for training.

    All data is Faker-generated — no real PII.  Uses a fixed seed for
    deterministic behaviour across test runs.

    Returns:
        DataFrame with columns: id (int), age (int), salary (int), dept (str).
    """
    fake = Faker()
    Faker.seed(12345)

    rows = [
        {
            "id": i,
            "age": fake.random_int(min=18, max=80),
            "salary": fake.random_int(min=30000, max=150000),
            "dept": fake.random_element(["Engineering", "Marketing", "Sales", "HR"]),
        }
        for i in range(1, 101)
    ]
    return pd.DataFrame(rows)


@pytest.fixture
def persons_parquet(persons_df: pd.DataFrame) -> str:
    """Write persons_df to a temporary Parquet file.

    Returns:
        Absolute path to the Parquet file.  The TemporaryDirectory is managed
        for the lifetime of the test.
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        path = str(Path(tmpdir) / "persons.parquet")
        persons_df.to_parquet(path, index=False, engine="pyarrow")
        yield path  # type: ignore[misc]


# ---------------------------------------------------------------------------
# AC4: train with DP-SGD enabled, verify epsilon_spent > 0
# ---------------------------------------------------------------------------


class TestDPWiringEpsilonSpent:
    """AC4: epsilon_spent(delta=1e-5) > 0 after training with dp_wrapper."""

    def test_epsilon_spent_positive_after_dp_training(self, persons_parquet: str) -> None:
        """AC4: Train SynthesisEngine with build_dp_wrapper(); epsilon_spent > 0.

        This is the primary end-to-end integration test for T7.3.
        Verifies the full wiring:
          - build_dp_wrapper() constructs a DPTrainingWrapper.
          - SynthesisEngine.train(dp_wrapper=...) routes to DPCompatibleCTGAN.
          - DPCompatibleCTGAN.fit() invokes the Opacus PrivacyEngine.
          - After training, wrapper.epsilon_spent(delta=1e-5) returns a
            positive value (Opacus has tracked at least one gradient step).
        """
        from synth_engine.bootstrapper.main import build_dp_wrapper, build_synthesis_engine

        wrapper = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=1.1)
        engine = build_synthesis_engine(epochs=2)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            engine.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper,
            )

        epsilon = wrapper.epsilon_spent(delta=1e-5)

        assert epsilon > 0.0, (
            f"epsilon_spent(delta=1e-5) must be > 0 after DP training, got {epsilon}. "
            "Opacus PrivacyEngine must have been activated and at least one gradient "
            "step must have been tracked."
        )

    def test_epsilon_is_finite_after_dp_training(self, persons_parquet: str) -> None:
        """epsilon_spent must be a finite float after training.

        Guards against Opacus returning nan or inf for degenerate configs.
        """
        import math

        from synth_engine.bootstrapper.main import build_dp_wrapper, build_synthesis_engine

        wrapper = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=1.1)
        engine = build_synthesis_engine(epochs=2)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            engine.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper,
            )

        epsilon = wrapper.epsilon_spent(delta=1e-5)

        assert math.isfinite(epsilon), f"epsilon_spent must be a finite float, got {epsilon}."


# ---------------------------------------------------------------------------
# AC5: budget exhaustion raises BudgetExhaustionError
# ---------------------------------------------------------------------------


class TestDPWiringBudgetExhaustion:
    """AC5: BudgetExhaustionError raised when allocated_epsilon is very low.

    Sets allocated_epsilon to an absurdly small value (e.g. 1e-10) so that
    the budget is exhausted immediately after the first gradient step.
    """

    def test_budget_exhaustion_raises_error(self, persons_parquet: str) -> None:
        """AC5: check_budget() raises BudgetExhaustionError when epsilon overspent.

        Train with dp_wrapper, then call check_budget() with a tiny
        allocated_epsilon that is guaranteed to be less than what Opacus
        spent during even a single gradient step.
        """
        from synth_engine.bootstrapper.main import build_dp_wrapper, build_synthesis_engine
        from synth_engine.modules.privacy.dp_engine import BudgetExhaustionError

        wrapper = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=1.1)
        engine = build_synthesis_engine(epochs=2)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            engine.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper,
            )

        # epsilon_spent after 2 epochs is definitely > 1e-10
        epsilon_after = wrapper.epsilon_spent(delta=1e-5)
        assert epsilon_after > 0, "Precondition: must have spent some epsilon."

        # Now check_budget with an impossibly small allocated_epsilon
        with pytest.raises(BudgetExhaustionError):
            wrapper.check_budget(allocated_epsilon=1e-10, delta=1e-5)

    def test_budget_not_exhausted_with_large_allocation(self, persons_parquet: str) -> None:
        """check_budget() must NOT raise when epsilon_spent < allocated_epsilon.

        Verifies the happy path: a generous allocated_epsilon means no exception.
        """
        from synth_engine.bootstrapper.main import build_dp_wrapper, build_synthesis_engine

        wrapper = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=1.1)
        engine = build_synthesis_engine(epochs=2)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            engine.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper,
            )

        # A very large allocated_epsilon means the budget can never be exhausted
        # in 2 epochs — this must not raise.
        wrapper.check_budget(allocated_epsilon=1_000_000.0, delta=1e-5)


# ---------------------------------------------------------------------------
# AC6: PrivacyEngine.get_epsilon(delta) consistent with training config
# ---------------------------------------------------------------------------


class TestDPWiringEpsilonConsistency:
    """AC6: PrivacyEngine.get_epsilon(delta) consistent with training config.

    Higher noise_multiplier → stronger privacy → lower epsilon (better).
    Lower noise_multiplier → weaker privacy → higher epsilon (worse).
    """

    def test_higher_noise_multiplier_gives_lower_epsilon(self, persons_parquet: str) -> None:
        """AC6: Larger noise_multiplier must yield lower or equal epsilon_spent.

        Trains two wrappers on the same data (same epochs):
          - wrapper_noisy: noise_multiplier=2.0 (more noise → better privacy)
          - wrapper_quiet: noise_multiplier=0.5 (less noise → worse privacy)

        The noisy wrapper must have a lower epsilon than the quiet one,
        consistent with the privacy-utility tradeoff in DP-SGD.
        """
        from synth_engine.bootstrapper.main import build_dp_wrapper, build_synthesis_engine

        wrapper_noisy = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=2.0)
        wrapper_quiet = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=0.5)

        engine_noisy = build_synthesis_engine(epochs=2)
        engine_quiet = build_synthesis_engine(epochs=2)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            engine_noisy.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper_noisy,
            )

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            engine_quiet.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper_quiet,
            )

        epsilon_noisy = wrapper_noisy.epsilon_spent(delta=1e-5)
        epsilon_quiet = wrapper_quiet.epsilon_spent(delta=1e-5)

        assert epsilon_noisy < epsilon_quiet, (
            f"Higher noise_multiplier must yield lower epsilon. "
            f"noisy (nm=2.0): epsilon={epsilon_noisy:.4f}, "
            f"quiet (nm=0.5): epsilon={epsilon_quiet:.4f}. "
            "Larger Gaussian noise → stronger DP guarantee → lower epsilon."
        )

    def test_epsilon_returns_float(self, persons_parquet: str) -> None:
        """AC6: epsilon_spent() must return a Python float."""
        from synth_engine.bootstrapper.main import build_dp_wrapper, build_synthesis_engine

        wrapper = build_dp_wrapper(max_grad_norm=1.0, noise_multiplier=1.1)
        engine = build_synthesis_engine(epochs=2)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            engine.train(
                table_name="persons",
                parquet_path=persons_parquet,
                dp_wrapper=wrapper,
            )

        epsilon = wrapper.epsilon_spent(delta=1e-5)

        assert isinstance(epsilon, float), f"epsilon_spent() must return float, got {type(epsilon)}"

    def test_epsilon_before_wrap_is_zero(self) -> None:
        """epsilon_spent() before wrap() must return 0.0.

        Verifies that the 'not-wrapped' state correctly reports 0.0 epsilon.
        This ensures no phantom epsilon is reported before training starts.
        """
        from synth_engine.modules.privacy.dp_engine import DPTrainingWrapper

        wrapper = DPTrainingWrapper()

        epsilon = wrapper.epsilon_spent(delta=1e-5)

        assert epsilon == 0.0, f"epsilon_spent() before wrap() must be 0.0, got {epsilon}"
