#!/usr/bin/env bash
# =============================================================================
# rotate-mtls-certs.sh — mTLS Leaf Certificate Rotation Helper
#
# Rotates leaf certificates for all mTLS services while preserving the
# existing Certificate Authority (CA).  The CA is never regenerated by this
# script — CA rotation requires a planned maintenance window (see Section
# 13.4 of docs/OPERATOR_MANUAL.md).
#
# What this script does:
#   1. Verifies that the CA key and certificate exist (prerequisite).
#   2. Backs up the current cert directory to backup-YYYYMMDD-HHMMSS/.
#   3. Generates new leaf certificates using the existing CA.
#   4. Validates new certs: chain verification, key-pair match, expiry > 30d.
#   5. Prints reload commands for each service (operator runs them manually).
#
# What this script does NOT do:
#   - Automatically reload services (operator runs reload commands for safety).
#   - Regenerate the CA (use generate-mtls-certs.sh --force only with planning).
#   - Send network traffic (fully air-gap compatible).
#
# Exit codes:
#   0  Success — new certs written and validated; run reload commands below.
#   1  Validation failure — new certs failed chain/expiry/key-pair check.
#   2  Prerequisite failure — CA key missing or OpenSSL unavailable.
#
# Usage:
#   ./scripts/rotate-mtls-certs.sh [OPTIONS]
#
# Options:
#   --output-dir DIR  Directory containing current certs (default: secrets/mtls).
#   --leaf-days N     New leaf certificate validity in days (default: 90).
#   -h, --help        Show this help message.
#
# Prerequisites:
#   openssl 1.1.1+ (checked at startup)
#
# Security notes:
#   - The CA private key (ca.key) must never be mounted into any container.
#   - This script reads ca.key only from the operator host.
#   - All new private key files are created with 0600 permissions.
#   - Backups retain original permissions.
#   - Backup directories are created with 0700 (owner-only) permissions to
#     prevent world-readable access to private key copies.
#   - --output-dir is canonicalized via realpath to prevent path traversal.
#   - Idempotent: running twice rotates certs twice (each run creates a new
#     time-stamped backup, so re-running is safe and the backup is preserved).
#
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Constants — hardcoded service allowlist (no arbitrary input)
# ---------------------------------------------------------------------------

readonly SERVICES=("app" "postgres" "pgbouncer" "redis")

# SANs for each service: Docker Compose hostname + Kubernetes FQDN variants
declare -A SERVICE_SANS
SERVICE_SANS["app"]="DNS:app,DNS:app.synth-engine.svc.cluster.local,DNS:app.synth-engine"
SERVICE_SANS["postgres"]="DNS:postgres,DNS:postgres.synth-engine.svc.cluster.local,DNS:postgres.synth-engine"
SERVICE_SANS["pgbouncer"]="DNS:pgbouncer,DNS:pgbouncer.synth-engine.svc.cluster.local,DNS:pgbouncer.synth-engine"
SERVICE_SANS["redis"]="DNS:redis,DNS:redis.synth-engine.svc.cluster.local,DNS:redis.synth-engine"

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

OUTPUT_DIR="secrets/mtls"
LEAF_DAYS=90
MIN_EXPIRY_DAYS=30

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

log() {
    printf '[rotate-mtls-certs] %s\n' "$*" >&2
}

die() {
    log "ERROR: $*"
    exit 2
}

validation_die() {
    log "VALIDATION FAILED: $*"
    exit 1
}

usage() {
    sed -n '/^# Usage:/,/^# =====/{ /^# =====/d; s/^# \{0,\}//; p }' "$0"
    exit 0
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output-dir)
            [[ $# -ge 2 ]] || die "--output-dir requires a directory argument"
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --leaf-days)
            [[ $# -ge 2 ]] || die "--leaf-days requires an integer argument"
            LEAF_DAYS="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            die "Unknown option: $1 (use --help for usage)"
            ;;
    esac
done

# ---------------------------------------------------------------------------
# Canonicalize OUTPUT_DIR to prevent path traversal (Finding 4: T46.3 review)
# realpath resolves symlinks and collapses ../ sequences.
# ---------------------------------------------------------------------------

OUTPUT_DIR="$(realpath "$OUTPUT_DIR")"

# Warn if the resolved path escapes the expected secrets/ subtree.
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
EXPECTED_PREFIX="$SCRIPT_DIR/secrets"
if [[ "$OUTPUT_DIR" != "$EXPECTED_PREFIX"* ]]; then
    log "WARNING: --output-dir resolved to '$OUTPUT_DIR', which is outside the expected secrets/ directory."
    log "         Ensure this is intentional before continuing."
fi

# ---------------------------------------------------------------------------
# Validate numeric args
# ---------------------------------------------------------------------------

[[ "$LEAF_DAYS" =~ ^[1-9][0-9]*$ ]] || die "--leaf-days must be a positive integer (got: $LEAF_DAYS)"

if [[ "$LEAF_DAYS" -lt 1 ]]; then
    die "--leaf-days must be at least 1 (got: $LEAF_DAYS)"
fi
if [[ "$LEAF_DAYS" -gt 825 ]]; then
    log "WARNING: --leaf-days $LEAF_DAYS exceeds Apple/browser trust limit of 825 days"
fi

# ---------------------------------------------------------------------------
# Prerequisite: openssl version check
# ---------------------------------------------------------------------------

if ! command -v openssl >/dev/null 2>&1; then
    die "openssl is not installed or not on PATH"
fi

OPENSSL_VERSION="$(openssl version 2>/dev/null)"
log "Using: $OPENSSL_VERSION"

OPENSSL_MAJOR="$(openssl version | awk '{print $2}' | cut -d. -f1)"
OPENSSL_MINOR="$(openssl version | awk '{print $2}' | cut -d. -f2)"

if [[ "$OPENSSL_MAJOR" -lt 1 ]] || \
   { [[ "$OPENSSL_MAJOR" -eq 1 ]] && [[ "$OPENSSL_MINOR" -lt 1 ]]; }; then
    die "openssl 1.1.1+ required (found: $OPENSSL_VERSION)"
fi

# ---------------------------------------------------------------------------
# Prerequisite: CA key and cert must already exist
# ---------------------------------------------------------------------------

CA_KEY="$OUTPUT_DIR/ca.key"
CA_CERT="$OUTPUT_DIR/ca.crt"

if [[ ! -f "$CA_KEY" ]]; then
    die "CA key not found at $CA_KEY — run generate-mtls-certs.sh first"
fi
if [[ ! -f "$CA_CERT" ]]; then
    die "CA cert not found at $CA_CERT — run generate-mtls-certs.sh first"
fi
if [[ ! -r "$CA_KEY" ]]; then
    die "CA key at $CA_KEY is not readable — check permissions (should be 0400)"
fi

log "CA verified: $CA_CERT"

# ---------------------------------------------------------------------------
# Step 1: Backup current certs
# ---------------------------------------------------------------------------

BACKUP_TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP_DIR="$OUTPUT_DIR/backup-${BACKUP_TIMESTAMP}"

log ""
log "Step 1/4: Backing up current certs to $BACKUP_DIR ..."
# Use 0700 (owner-only) so private key copies in the backup are not
# world-readable regardless of the operator's umask (Finding 2: T46.3 review).
mkdir -p "$BACKUP_DIR" && chmod 0700 "$BACKUP_DIR"

for SERVICE in "${SERVICES[@]}"; do
    for EXT in crt key; do
        FILE="$OUTPUT_DIR/${SERVICE}.${EXT}"
        if [[ -f "$FILE" ]]; then
            cp "$FILE" "$BACKUP_DIR/"
            log "  Backed up: $FILE"
        fi
    done
done

# Also back up CA cert (not key — already in OUTPUT_DIR)
if [[ -f "$CA_CERT" ]]; then
    cp "$CA_CERT" "$BACKUP_DIR/"
fi

log "  Backup complete: $BACKUP_DIR"

# ---------------------------------------------------------------------------
# Step 2: Generate new leaf certificates (CA is preserved)
# ---------------------------------------------------------------------------

log ""
log "Step 2/4: Generating new leaf certificates (CA preserved) ..."

TMPDIR_WORK="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_WORK"' EXIT

for SERVICE in "${SERVICES[@]}"; do
    LEAF_KEY="$OUTPUT_DIR/${SERVICE}.key"
    LEAF_CERT="$OUTPUT_DIR/${SERVICE}.crt"
    LEAF_CSR="$TMPDIR_WORK/${SERVICE}.csr"
    EXT_FILE="$TMPDIR_WORK/${SERVICE}.ext"
    SAN_VALUE="${SERVICE_SANS[$SERVICE]}"

    log "  Generating leaf certificate for: $SERVICE"

    # Private key
    openssl ecparam -name prime256v1 -genkey -noout -out "$LEAF_KEY"
    chmod 0600 "$LEAF_KEY"

    # CSR
    openssl req -new \
        -key "$LEAF_KEY" \
        -out "$LEAF_CSR" \
        -subj "/CN=${SERVICE}/O=Conclave Engine/OU=mTLS Leaf"

    # Extension file for SANs
    cat > "$EXT_FILE" <<EXTEOF
[v3_req]
basicConstraints = critical,CA:false
keyUsage = critical,digitalSignature,keyEncipherment
extendedKeyUsage = serverAuth,clientAuth
subjectAltName = ${SAN_VALUE}
EXTEOF

    # Sign with CA
    openssl x509 -req \
        -in "$LEAF_CSR" \
        -CA "$CA_CERT" \
        -CAkey "$CA_KEY" \
        -CAcreateserial \
        -out "$LEAF_CERT" \
        -days "$LEAF_DAYS" \
        -extensions v3_req \
        -extfile "$EXT_FILE"

    log "    Certificate: $LEAF_CERT (valid $LEAF_DAYS days)"
    log "    Private key: $LEAF_KEY (0600)"
done

# ---------------------------------------------------------------------------
# Step 3: Validate new certs (chain, expiry, key-pair)
# ---------------------------------------------------------------------------

log ""
log "Step 3/4: Validating new certificates ..."

VALIDATION_PASSED=true

for SERVICE in "${SERVICES[@]}"; do
    LEAF_KEY="$OUTPUT_DIR/${SERVICE}.key"
    LEAF_CERT="$OUTPUT_DIR/${SERVICE}.crt"

    # 3a. Chain verification
    if ! openssl verify -CAfile "$CA_CERT" "$LEAF_CERT" >/dev/null 2>&1; then
        log "  FAIL: Chain verification failed for $SERVICE"
        VALIDATION_PASSED=false
        continue
    fi

    # 3b. Expiry check: must have > MIN_EXPIRY_DAYS remaining
    EXPIRY_EPOCH="$(openssl x509 -noout -enddate -in "$LEAF_CERT" 2>/dev/null | cut -d= -f2)"
    EXPIRY_TIMESTAMP="$(date -d "$EXPIRY_EPOCH" +%s 2>/dev/null || date -j -f "%b %e %T %Y %Z" "$EXPIRY_EPOCH" +%s 2>/dev/null || echo 0)"
    NOW_TIMESTAMP="$(date +%s)"
    DAYS_LEFT=$(( (EXPIRY_TIMESTAMP - NOW_TIMESTAMP) / 86400 ))

    if [[ "$DAYS_LEFT" -lt "$MIN_EXPIRY_DAYS" ]]; then
        log "  FAIL: $SERVICE cert expires in only $DAYS_LEFT days (minimum required: $MIN_EXPIRY_DAYS)"
        VALIDATION_PASSED=false
        continue
    fi

    # 3c. Key-pair match: compare public key bytes from cert and key
    CERT_PUBKEY="$(openssl x509 -noout -pubkey -in "$LEAF_CERT" 2>/dev/null)"
    KEY_PUBKEY="$(openssl ec -pubout -in "$LEAF_KEY" 2>/dev/null)"

    if [[ "$CERT_PUBKEY" != "$KEY_PUBKEY" ]]; then
        log "  FAIL: Key/cert mismatch for $SERVICE (private key does not match certificate)"
        VALIDATION_PASSED=false
        continue
    fi

    log "  OK: $SERVICE — chain valid, $DAYS_LEFT days remaining, key matches cert"
done

if [[ "$VALIDATION_PASSED" != "true" ]]; then
    log ""
    log "ROTATION ABORTED: One or more certificates failed validation."
    log "The new (failing) certs remain in $OUTPUT_DIR."
    log "The previous certs are preserved in $BACKUP_DIR."
    log "To restore, copy the backup certs back:"
    log "  cp $BACKUP_DIR/*.crt $BACKUP_DIR/*.key $OUTPUT_DIR/"
    validation_die "Certificate validation failed — see log above for details"
fi

# ---------------------------------------------------------------------------
# Step 4: Print reload commands for operator
# ---------------------------------------------------------------------------

log ""
log "Step 4/4: New certificates validated. Run the following reload commands:"
log ""
log "  Docker Compose:"
log "    # PgBouncer: supports live config reload without connection drops"
log "    docker compose exec pgbouncer psql -U pgbouncer pgbouncer -c 'RELOAD;'"
log ""
log "    # Redis: update TLS config live (no connection drops on reload)"
log "    REDIS_CA=\$(cat $OUTPUT_DIR/ca.crt)"
log "    REDIS_CERT=\$(cat $OUTPUT_DIR/redis.crt)"
log "    REDIS_KEY=\$(cat $OUTPUT_DIR/redis.key)"
log "    docker compose exec redis redis-cli CONFIG SET \\"
log "        tls-ca-cert-file $OUTPUT_DIR/ca.crt \\"
log "        tls-cert-file $OUTPUT_DIR/redis.crt \\"
log "        tls-key-file $OUTPUT_DIR/redis.key"
log ""
log "    # PostgreSQL: reloads TLS config without dropping existing connections"
log "    docker compose exec postgres psql -U postgres -c 'SELECT pg_reload_conf();'"
log ""
log "    # App container: uvicorn does NOT support dynamic TLS reload."
log "    # A rolling restart is required (brief reconnect window):"
log "    docker compose up -d --no-deps --force-recreate app"
log ""
log "  Kubernetes:"
log "    # Update the TLS secret with new certs:"
log "    kubectl create secret generic conclave-mtls \\"
log "        --from-file=ca.crt=$OUTPUT_DIR/ca.crt \\"
log "        --from-file=app.crt=$OUTPUT_DIR/app.crt \\"
log "        --from-file=app.key=$OUTPUT_DIR/app.key \\"
log "        --from-file=postgres.crt=$OUTPUT_DIR/postgres.crt \\"
log "        --from-file=postgres.key=$OUTPUT_DIR/postgres.key \\"
log "        --from-file=pgbouncer.crt=$OUTPUT_DIR/pgbouncer.crt \\"
log "        --from-file=pgbouncer.key=$OUTPUT_DIR/pgbouncer.key \\"
log "        --from-file=redis.crt=$OUTPUT_DIR/redis.crt \\"
log "        --from-file=redis.key=$OUTPUT_DIR/redis.key \\"
log "        --dry-run=client -o yaml | kubectl apply -f -"
log ""
log "    # Trigger rolling restart for all affected deployments:"
log "    kubectl rollout restart deployment/conclave-app"
log "    kubectl rollout restart deployment/conclave-pgbouncer"
log "    kubectl rollout restart statefulset/conclave-postgres"
log "    kubectl rollout restart statefulset/conclave-redis"
log ""
log "==========================================================================="
log "Certificate rotation complete."
log "  Output directory  : $OUTPUT_DIR"
log "  Backup directory  : $BACKUP_DIR"
log "  New validity      : $LEAF_DAYS days"
log "==========================================================================="
log ""
log "IMPORTANT:"
log "  - Run the reload commands above to activate the new certificates."
log "  - During the rolling restart of the app container, existing connections"
log "    will be briefly dropped.  Clients with retry logic will reconnect"
log "    automatically.  See docs/OPERATOR_MANUAL.md Section 13 for details."
log "  - Verify the new chain after reload:"
log "    openssl verify -CAfile $OUTPUT_DIR/ca.crt $OUTPUT_DIR/app.crt"
