"""Sample data seeding script for the Conclave Engine E2E validation.

Generates realistic multi-table fictional data using Faker with a deterministic
seed to ensure reproducibility. All data is synthetic — no real PII is used.

Tables generated:
- customers  (id, first_name, last_name, email, ssn, phone, address, created_at)
- orders     (id, customer_id FK->customers, order_date, total_amount, status)
- order_items (id, order_id FK->orders, product_name, quantity, unit_price)
- payments   (id, order_id FK->orders, payment_date, amount, payment_method)

Usage:
    # Export CSV files to sample_data/ and print DDL to stdout (default)
    poetry run python3 scripts/seed_sample_data.py

    # Specify output directory and record counts
    poetry run python3 scripts/seed_sample_data.py \\
        --output-dir sample_data \\
        --customers 200 \\
        --orders 500 \\
        --items-per-order 3 \\
        --seed 42

    # Also execute DDL+INSERTs against a PostgreSQL database
    poetry run python3 scripts/seed_sample_data.py \\
        --dsn postgresql://conclave:conclave@localhost:5432/conclave_source

Task: P18-T18.3 — End-to-End Validation with Sample Data
CONSTITUTION Priority 0: All data is generated by Faker. No real PII is committed.
"""

from __future__ import annotations

import csv
import datetime
import logging
import random
import sys
from pathlib import Path
from typing import Any

import click
from faker import Faker

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_SEED: int = 42
DEFAULT_CUSTOMERS: int = 100
DEFAULT_ORDERS: int = 250
DEFAULT_ITEMS_PER_ORDER: int = 3
DEFAULT_OUTPUT_DIR: str = "sample_data"

# Fixed reference epoch for deterministic timestamp generation.
# All generated timestamps are computed as offsets from this anchor date so
# that generate_* functions produce identical output across invocations when
# called with the same seed, regardless of the wall-clock time.
_EPOCH: datetime.datetime = datetime.datetime(2024, 1, 1, 0, 0, 0, tzinfo=datetime.UTC)

ORDER_STATUSES: tuple[str, ...] = (
    "pending",
    "processing",
    "shipped",
    "delivered",
    "cancelled",
)

PAYMENT_METHODS: tuple[str, ...] = (
    "credit_card",
    "debit_card",
    "bank_transfer",
    "paypal",
    "cash",
)

PRODUCT_NAMES: tuple[str, ...] = (
    "Wireless Headphones",
    "USB-C Hub",
    "Mechanical Keyboard",
    "4K Monitor",
    "Laptop Stand",
    "Mouse Pad",
    "Webcam HD",
    "External SSD 1TB",
    "LED Desk Lamp",
    "Ergonomic Chair",
    "Standing Desk Mat",
    "Cable Management Kit",
    "Screen Protector",
    "Phone Case",
    "Charging Dock",
    "Smart Speaker",
    "Graphics Tablet",
    "Noise-Cancelling Earbuds",
    "Portable Charger",
    "HDMI Cable 2m",
)


# ---------------------------------------------------------------------------
# DDL builder
# ---------------------------------------------------------------------------


def build_ddl() -> str:
    """Return PostgreSQL DDL for all four sample tables.

    Includes primary keys, foreign key references, and appropriate column
    types for the schema defined in the P18-T18.3 backlog spec.

    Returns:
        A string containing CREATE TABLE statements for all four tables.
    """
    return """\
-- Conclave Engine — Sample Data DDL
-- Generated by scripts/seed_sample_data.py (P18-T18.3)
-- All data is fictional. No real PII.

CREATE TABLE IF NOT EXISTS customers (
    id          SERIAL PRIMARY KEY,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    ssn         VARCHAR(11)  NOT NULL,
    phone       VARCHAR(30)  NOT NULL,
    address     TEXT         NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS orders (
    id            SERIAL PRIMARY KEY,
    customer_id   INTEGER      NOT NULL REFERENCES customers(id),
    order_date    TIMESTAMP    NOT NULL,
    total_amount  NUMERIC(10,2) NOT NULL,
    status        VARCHAR(20)  NOT NULL
);

CREATE TABLE IF NOT EXISTS order_items (
    id            SERIAL PRIMARY KEY,
    order_id      INTEGER      NOT NULL REFERENCES orders(id),
    product_name  VARCHAR(200) NOT NULL,
    quantity      INTEGER      NOT NULL CHECK (quantity > 0),
    unit_price    NUMERIC(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS payments (
    id              SERIAL PRIMARY KEY,
    order_id        INTEGER      NOT NULL REFERENCES orders(id),
    payment_date    TIMESTAMP    NOT NULL,
    amount          NUMERIC(10,2) NOT NULL,
    payment_method  VARCHAR(30)  NOT NULL
);
"""


# ---------------------------------------------------------------------------
# Data generators
# ---------------------------------------------------------------------------


def generate_customers(
    n: int = DEFAULT_CUSTOMERS,
    seed: int = DEFAULT_SEED,
) -> list[dict[str, Any]]:
    """Generate a list of fictional customer records.

    Uses a seeded Faker instance to ensure deterministic, reproducible output.
    All values are purely fictional; no real PII is included.

    Timestamps are computed as offsets from the fixed ``_EPOCH`` constant so
    that the output is identical across multiple calls with the same seed,
    regardless of wall-clock time.

    Args:
        n: Number of customer records to generate.
        seed: Deterministic seed for Faker and Python random module.

    Returns:
        A list of dicts with keys matching the customers table schema.
    """
    Faker.seed(seed)
    fake = Faker()
    rng = random.Random(seed)  # noqa: S311  # nosec B311 — PRNG for fictional data generation, not cryptographic use
    customers: list[dict[str, Any]] = []
    for i in range(1, n + 1):
        # Build a realistic timestamp spread over the last 3 years from _EPOCH.
        # Using _EPOCH (not datetime.now()) guarantees deterministic output.
        days_ago = rng.randint(0, 1095)
        created_at = _EPOCH - datetime.timedelta(days=days_ago)
        customers.append(
            {
                "id": i,
                "first_name": fake.first_name(),
                "last_name": fake.last_name(),
                "email": f"user{i}_{fake.email()}",
                "ssn": fake.ssn(),
                "phone": fake.phone_number(),
                "address": fake.address().replace("\n", ", "),
                "created_at": created_at.strftime("%Y-%m-%d %H:%M:%S"),
            }
        )
    return customers


def generate_orders(
    customers: list[dict[str, Any]],
    n: int = DEFAULT_ORDERS,
    seed: int = DEFAULT_SEED,
) -> list[dict[str, Any]]:
    """Generate a list of fictional order records referencing provided customers.

    Timestamps are computed as offsets from the fixed ``_EPOCH`` constant so
    that the output is identical across multiple calls with the same seed.

    Args:
        customers: Customer records produced by generate_customers().
                   Each order's customer_id references a customer's id.
        n: Number of order records to generate.
        seed: Deterministic seed for Faker and Python random module.

    Returns:
        A list of dicts with keys matching the orders table schema.
    """
    rng = random.Random(seed)  # noqa: S311  # nosec B311 — PRNG for fictional data generation, not cryptographic use
    customer_ids = [c["id"] for c in customers]
    orders: list[dict[str, Any]] = []
    for i in range(1, n + 1):
        days_ago = rng.randint(0, 730)
        order_date = _EPOCH - datetime.timedelta(days=days_ago)
        total_amount = round(rng.uniform(9.99, 2499.99), 2)
        orders.append(
            {
                "id": i,
                "customer_id": rng.choice(customer_ids),
                "order_date": order_date.strftime("%Y-%m-%d %H:%M:%S"),
                "total_amount": f"{total_amount:.2f}",
                "status": rng.choice(ORDER_STATUSES),
            }
        )
    return orders


def generate_order_items(
    orders: list[dict[str, Any]],
    n: int | None = None,
    seed: int = DEFAULT_SEED,
    items_per_order: int = DEFAULT_ITEMS_PER_ORDER,
) -> list[dict[str, Any]]:
    """Generate fictional order line items referencing provided orders.

    Args:
        orders: Order records produced by generate_orders(). Each item's
                order_id references an order's id.
        n: Total number of items to generate. If None, generates
           items_per_order items for each order.
        seed: Deterministic seed for random generation.
        items_per_order: Items per order when n is None.

    Returns:
        A list of dicts with keys matching the order_items table schema.
    """
    rng = random.Random(seed)  # noqa: S311  # nosec B311 — PRNG for fictional data generation, not cryptographic use
    order_ids = [o["id"] for o in orders]
    items: list[dict[str, Any]] = []

    if n is not None:
        # Generate exactly n items, randomly distributed across orders
        for i in range(1, n + 1):
            unit_price = round(rng.uniform(0.99, 499.99), 2)
            items.append(
                {
                    "id": i,
                    "order_id": rng.choice(order_ids),
                    "product_name": rng.choice(PRODUCT_NAMES),
                    "quantity": rng.randint(1, 10),
                    "unit_price": f"{unit_price:.2f}",
                }
            )
    else:
        # Generate items_per_order items for each order in sequence
        item_id = 1
        for order_id in order_ids:
            count = rng.randint(1, items_per_order * 2)
            for _ in range(count):
                unit_price = round(rng.uniform(0.99, 499.99), 2)
                items.append(
                    {
                        "id": item_id,
                        "order_id": order_id,
                        "product_name": rng.choice(PRODUCT_NAMES),
                        "quantity": rng.randint(1, 10),
                        "unit_price": f"{unit_price:.2f}",
                    }
                )
                item_id += 1

    return items


def generate_payments(
    orders: list[dict[str, Any]],
    n: int | None = None,
    seed: int = DEFAULT_SEED,
) -> list[dict[str, Any]]:
    """Generate fictional payment records referencing provided orders.

    When n is None, generates exactly one payment per order using the order's
    total_amount. When n is provided, generates exactly n payments distributed
    randomly across orders.

    Timestamps are computed as offsets from the fixed ``_EPOCH`` constant so
    that the output is identical across multiple calls with the same seed.

    Args:
        orders: Order records produced by generate_orders(). Each payment's
                order_id references an order's id.
        n: Total number of payments to generate. If None, generates exactly
           one payment per order.
        seed: Deterministic seed for random generation.

    Returns:
        A list of dicts with keys matching the payments table schema.
    """
    rng = random.Random(seed)  # noqa: S311  # nosec B311 — PRNG for fictional data generation, not cryptographic use
    order_ids = [o["id"] for o in orders]
    payments: list[dict[str, Any]] = []

    if n is not None:
        # Generate exactly n payments distributed across orders
        for i in range(1, n + 1):
            days_ago = rng.randint(0, 30)
            payment_date = _EPOCH - datetime.timedelta(days=days_ago)
            amount = round(rng.uniform(9.99, 2499.99), 2)
            payments.append(
                {
                    "id": i,
                    "order_id": rng.choice(order_ids),
                    "payment_date": payment_date.strftime("%Y-%m-%d %H:%M:%S"),
                    "amount": f"{amount:.2f}",
                    "payment_method": rng.choice(PAYMENT_METHODS),
                }
            )
    else:
        payment_id = 1
        for order in orders:
            # Every order gets at least one payment
            days_ago = rng.randint(0, 30)
            payment_date = _EPOCH - datetime.timedelta(days=days_ago)
            total = float(order["total_amount"])
            payments.append(
                {
                    "id": payment_id,
                    "order_id": order["id"],
                    "payment_date": payment_date.strftime("%Y-%m-%d %H:%M:%S"),
                    "amount": f"{total:.2f}",
                    "payment_method": rng.choice(PAYMENT_METHODS),
                }
            )
            payment_id += 1

    return payments


# ---------------------------------------------------------------------------
# CSV export
# ---------------------------------------------------------------------------

# Column order for each table — must match backlog spec exactly
_COLUMN_ORDER: dict[str, list[str]] = {
    "customers": [
        "id",
        "first_name",
        "last_name",
        "email",
        "ssn",
        "phone",
        "address",
        "created_at",
    ],
    "orders": ["id", "customer_id", "order_date", "total_amount", "status"],
    "order_items": ["id", "order_id", "product_name", "quantity", "unit_price"],
    "payments": ["id", "order_id", "payment_date", "amount", "payment_method"],
}


def export_csv(
    rows: list[dict[str, Any]],
    path: Path,
    table: str | None = None,
) -> None:
    """Write a list of row dicts to a CSV file.

    The CSV is written with a header row. If a table name is provided, the
    column order is taken from the canonical schema order in _COLUMN_ORDER.
    Otherwise, the order is derived from the first row's dict key order.

    Args:
        rows: List of dicts to serialise, each sharing the same key set.
        path: Destination file path. Parent directory is created if absent.
        table: Optional table name used to look up canonical column ordering.

    Raises:
        ValueError: If rows is empty and table is unknown (no columns to write).
    """
    if not rows:
        logger.warning("export_csv called with empty rows list for path=%s", path)
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str]
    if table and table in _COLUMN_ORDER:
        fieldnames = _COLUMN_ORDER[table]
    else:
        fieldnames = list(rows[0].keys())

    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    logger.info("Exported %d rows to %s", len(rows), path)


# ---------------------------------------------------------------------------
# DDL+INSERT execution (optional — requires live PostgreSQL)
# ---------------------------------------------------------------------------


def _execute_against_db(dsn: str, ddl: str, tables: dict[str, list[dict[str, Any]]]) -> None:
    """Execute DDL and INSERT statements against a PostgreSQL database.

    This function is gated behind an optional import of psycopg2 and is only
    called when --dsn is supplied. In offline/test mode, this code path is
    never executed.

    Args:
        dsn: PostgreSQL connection string.
        ddl: DDL string returned by build_ddl().
        tables: Dict mapping table name to list of row dicts.

    Raises:
        SystemExit: If psycopg2 is not importable.
        Exception: On database connection or execution errors.
    """
    try:
        import psycopg2
    except ImportError:
        logger.error("psycopg2 is not installed. Cannot connect to PostgreSQL.")
        sys.exit(1)

    logger.info("Connecting to database: %s", dsn.split("@")[-1])  # redact credentials
    conn = psycopg2.connect(dsn)
    try:
        conn.autocommit = False
        with conn.cursor() as cur:
            logger.info("Executing DDL...")
            cur.execute(ddl)
            for table_name, rows in tables.items():
                if not rows:
                    continue
                cols = _COLUMN_ORDER.get(table_name, list(rows[0].keys()))
                placeholders = ", ".join(["%s"] * len(cols))
                col_list = ", ".join(cols)
                sql = f"INSERT INTO {table_name} ({col_list}) VALUES ({placeholders})"  # noqa: S608  # nosec B608 — table_name and cols are from internal _COLUMN_ORDER dict, not user input
                values = [tuple(str(row[c]) for c in cols) for row in rows]
                cur.executemany(sql, values)
                logger.info("Inserted %d rows into %s", len(rows), table_name)
        conn.commit()
        logger.info("Transaction committed.")
    except psycopg2.Error:
        conn.rollback()
        logger.exception("Database error — transaction rolled back.")
        raise
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


@click.command()
@click.option(
    "--output-dir",
    default=DEFAULT_OUTPUT_DIR,
    show_default=True,
    help="Directory for CSV exports (relative to cwd or absolute).",
)
@click.option(
    "--customers",
    "n_customers",
    default=DEFAULT_CUSTOMERS,
    show_default=True,
    type=int,
    help="Number of customer records to generate.",
)
@click.option(
    "--orders",
    "n_orders",
    default=DEFAULT_ORDERS,
    show_default=True,
    type=int,
    help="Number of order records to generate.",
)
@click.option(
    "--items-per-order",
    default=DEFAULT_ITEMS_PER_ORDER,
    show_default=True,
    type=int,
    help="Average line items per order (used when --items is not set).",
)
@click.option(
    "--seed",
    default=DEFAULT_SEED,
    show_default=True,
    type=int,
    help="Deterministic random seed for reproducibility.",
)
@click.option(
    "--dsn",
    default=None,
    help=("PostgreSQL DSN to execute DDL+INSERTs against. If omitted, only CSV files are written."),
)
@click.option(
    "--print-ddl",
    is_flag=True,
    default=False,
    help="Print DDL to stdout before exporting CSVs.",
)
def main(
    output_dir: str,
    n_customers: int,
    n_orders: int,
    items_per_order: int,
    seed: int,
    dsn: str | None,
    print_ddl: bool,
) -> None:
    """Seed sample data for Conclave Engine end-to-end validation.

    Generates fictional multi-table data using Faker (deterministic seed) and
    writes CSV exports to OUTPUT_DIR. Optionally executes DDL + INSERTs against
    a PostgreSQL database when --dsn is provided.

    All generated data is purely fictional. No real PII is produced or committed.
    """
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
    )

    out = Path(output_dir)
    ddl = build_ddl()

    if print_ddl:
        click.echo(ddl)

    # --- Generate data ---
    logger.info("Generating %d customers (seed=%d)...", n_customers, seed)
    customers = generate_customers(n=n_customers, seed=seed)

    logger.info("Generating %d orders...", n_orders)
    orders = generate_orders(customers=customers, n=n_orders, seed=seed)

    logger.info("Generating order items (%d items/order avg)...", items_per_order)
    items = generate_order_items(orders=orders, seed=seed, items_per_order=items_per_order)

    logger.info("Generating payments (1 per order)...")
    payments = generate_payments(orders=orders, seed=seed)

    # --- Export CSVs ---
    export_csv(customers, out / "customers.csv", table="customers")
    export_csv(orders, out / "orders.csv", table="orders")
    export_csv(items, out / "order_items.csv", table="order_items")
    export_csv(payments, out / "payments.csv", table="payments")

    logger.info(
        "Sample data written to %s/ (%d customers, %d orders, %d items, %d payments)",
        output_dir,
        len(customers),
        len(orders),
        len(items),
        len(payments),
    )

    # --- Optional DB execution ---
    if dsn:
        tables = {
            "customers": customers,
            "orders": orders,
            "order_items": items,
            "payments": payments,
        }
        _execute_against_db(dsn=dsn, ddl=ddl, tables=tables)


if __name__ == "__main__":
    main()
