"""SQLModel table definition for the Organization entity.

An Organization is the root tenant in the multi-tenant data model.
All data-bearing resources (Connection, SynthesisJob, WebhookRegistration,
PrivacyLedger) carry an ``org_id`` FK that resolves to this table.

Seeding
-------
Migration 009 creates two default rows idempotently:

- Default organization: UUID ``00000000-0000-0000-0000-000000000000``
- These reserved UUIDs cannot be generated by ``uuid.uuid4()`` (version 4),
  ensuring no collision with real org IDs.

Import boundaries
-----------------
This module lives in ``shared/`` because Organization is consumed by:
- ``bootstrapper/routers/`` (all routers filter by org_id)
- ``modules/privacy/ledger.py`` (PrivacyLedger.org_id FK)
- ``modules/synthesizer/jobs/job_models.py`` (SynthesisJob.org_id FK)
- ``bootstrapper/schemas/connections.py`` (Connection.org_id FK)

Must NOT import from any module-specific package.

CONSTITUTION Priority 0: Security — tenant root; all isolation anchored here
CONSTITUTION Priority 5: Code Quality — strict typing, Google docstrings
Phase: 79 — Multi-Tenancy Foundation (T79.1)
"""

from __future__ import annotations

from datetime import UTC, datetime

from sqlmodel import Field

from synth_engine.shared.db import BaseModel


def _utcnow() -> datetime:
    """Return the current UTC time as a timezone-aware datetime.

    Returns:
        Current UTC time as a timezone-aware :class:`datetime`.
    """
    return datetime.now(UTC)


class Organization(BaseModel, table=True):
    """Database table for tenant organizations.

    Each row represents one tenant organization.  All data resources
    are associated with an organization via ``org_id`` FK.

    The ``id`` field overrides ``BaseModel.id`` with a string type for
    SQLite/PostgreSQL portability (same pattern as Connection and
    WebhookRegistration).  The UUID is stored as TEXT on SQLite and
    UUID on PostgreSQL.

    Attributes:
        id: UUID v4 primary key (stored as VARCHAR string).
        name: Human-readable organization name.
        created_at: UTC timestamp of organization creation.
        settings: Optional JSON blob for per-org configuration.
            Currently unused; reserved for P80+ per-tenant settings.
    """

    __tablename__ = "organizations"

    name: str = Field(..., index=True)
    settings: str | None = Field(default=None)
