"""Multi-tenant identity context and FastAPI dependency — Phase 79.

Provides:
- :class:`TenantContext`: frozen dataclass carrying ``(org_id, user_id, role)``
  resolved from the JWT bearer token.
- :func:`get_current_user`: FastAPI dependency that replaces the legacy
  :func:`~synth_engine.bootstrapper.dependencies.auth.get_current_operator`.

Identity Model (ADR-0065 — Option C: Short-Lived Embedded Claims)
------------------------------------------------------------------
JWT payload contains ``sub`` (user_id), ``org_id``, and ``role`` claims.
Token expiry is capped at 900 seconds (15 minutes) in multi-tenant mode to
bound the staleness window on org/role changes.

Pass-Through Sentinel
---------------------
When ``jwt_secret_key`` is empty in non-production mode, ``get_current_user``
returns a sentinel ``TenantContext`` with:

- ``org_id = "00000000-0000-0000-0000-000000000000"`` (default org UUID)
- ``user_id = "00000000-0000-0000-0000-000000000001"`` (default user UUID)
- ``role = "admin"``

These reserved all-zeros UUIDs cannot be generated by ``uuid.uuid4()``
(version 4), so they cannot collide with real tenant IDs (ATTACK-02).

Security Posture
----------------
- ``org_id`` is derived exclusively from the verified JWT ``org_id`` claim.
  HTTP headers (e.g., ``X-Org-ID``) are intentionally ignored.
- ``TenantContext`` is **frozen** — mutation after construction is forbidden.
  This prevents accidental privilege escalation in handler code.
- JWT without ``org_id`` claim is rejected with 401 (no legacy token upgrade).
- Production mode with empty ``jwt_secret_key`` returns 401 (same as
  :func:`get_current_operator`).

CONSTITUTION Priority 0: Security — JWT-derived identity only, no header spoofing
CONSTITUTION Priority 5: Code Quality — strict typing, Google docstrings
Phase: 79 — Multi-Tenancy Foundation (T79.2)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

from fastapi import HTTPException
from starlette.requests import Request

from synth_engine.bootstrapper.dependencies.auth import (
    AuthenticationError,
    verify_token,
)
from synth_engine.shared.settings import get_settings

_logger = logging.getLogger(__name__)

#: Default org UUID — reserved all-zeros UUID, cannot collide with UUIDv4.
DEFAULT_ORG_UUID: str = "00000000-0000-0000-0000-000000000000"

#: Default user UUID — reserved near-zeros UUID, cannot collide with UUIDv4.
DEFAULT_USER_UUID: str = "00000000-0000-0000-0000-000000000001"

#: Default role for pass-through (unconfigured/dev) mode.
DEFAULT_ROLE: str = "admin"


@dataclass(frozen=True)
class TenantContext:
    """Immutable resolved tenant identity for a single HTTP request.

    Constructed by :func:`get_current_user` from verified JWT claims.
    The frozen constraint prevents mutation after request boundary.

    Attributes:
        org_id: UUID string of the organization derived from the JWT
            ``org_id`` claim.  Never derived from HTTP headers.
        user_id: UUID string of the authenticated user derived from the
            JWT ``sub`` claim.
        role: RBAC role string derived from the JWT ``role`` claim.
            One of: ``admin``, ``operator``, ``viewer``, ``auditor``.
    """

    org_id: str
    user_id: str
    role: str


def get_current_user(request: Request) -> TenantContext:
    """Extract and return the tenant context from the JWT bearer token.

    FastAPI dependency for all tenant-scoped resource endpoints.
    Extracts the ``Authorization`` header, verifies the bearer token,
    and returns a :class:`TenantContext` with ``(org_id, user_id, role)``.

    **Pass-through mode (non-production only)**: Returns the default-org
    sentinel when ``jwt_secret_key`` is empty and NOT in production mode.
    Sentinel values: ``org_id=DEFAULT_ORG_UUID``, ``user_id=DEFAULT_USER_UUID``,
    ``role="admin"``.

    **Production hard-fail**: Returns 401 when ``jwt_secret_key`` is empty
    AND in production mode.  An empty JWT secret in production is a
    misconfiguration — pass-through is never permitted.

    **X-Org-ID header is ignored**: The ``org_id`` is derived exclusively
    from the verified JWT claim.  Any ``X-Org-ID`` header in the request is
    intentionally not read (ATTACK-02 mitigation from ADR-0065).

    Args:
        request: The incoming HTTP request (injected by FastAPI).

    Returns:
        :class:`TenantContext` with ``(org_id, user_id, role)`` from the
        verified JWT, or the pass-through sentinel in unconfigured non-production
        mode.

    Raises:
        HTTPException: 401 if the Authorization header is absent, malformed,
            the token is invalid/expired, the token is missing the ``org_id``
            claim, or ``jwt_secret_key`` is empty in production mode.
    """
    settings = get_settings()
    jwt_secret = settings.jwt_secret_key.get_secret_value()

    if not jwt_secret:
        if settings.is_production():
            raise HTTPException(
                status_code=401,
                detail="Authentication required. Provide a valid Bearer token.",
                headers={"WWW-Authenticate": "Bearer"},
            )
        # Non-production pass-through: return default-org sentinel.
        request.state.jwt_claims = {}
        return TenantContext(
            org_id=DEFAULT_ORG_UUID,
            user_id=DEFAULT_USER_UUID,
            role=DEFAULT_ROLE,
        )

    auth_header: str | None = request.headers.get("Authorization")
    if auth_header is None:
        raise HTTPException(
            status_code=401,
            detail="Authentication required. Provide a valid Bearer token.",
            headers={"WWW-Authenticate": "Bearer"},
        )

    if not auth_header.startswith("Bearer "):
        raise HTTPException(
            status_code=401,
            detail="Invalid Authorization header format. Expected: 'Bearer <token>'.",
            headers={"WWW-Authenticate": "Bearer"},
        )

    token = auth_header[len("Bearer ") :]

    try:
        claims = verify_token(token)
    except AuthenticationError as exc:
        _logger.debug(
            "JWT authentication failed: %s",
            type(exc).__name__,
            exc_info=True,
        )
        raise HTTPException(
            status_code=401,
            detail="Invalid credentials",
            headers={"WWW-Authenticate": "Bearer"},
        ) from exc

    # Extract sub → user_id
    sub = claims.get("sub")
    if not isinstance(sub, str) or not sub:
        raise HTTPException(
            status_code=401,
            detail="Token is missing required sub claim.",
            headers={"WWW-Authenticate": "Bearer"},
        )

    # Extract org_id — required in multi-tenant mode.
    # Legacy tokens without org_id are rejected (no silent upgrade).
    org_id = claims.get("org_id")
    if not isinstance(org_id, str) or not org_id:
        _logger.debug(
            "JWT rejected: missing or empty org_id claim. "
            "Multi-tenant mode requires org_id in JWT payload."
        )
        raise HTTPException(
            status_code=401,
            detail="Invalid credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )

    # Extract role — default to "operator" if absent for backward compat.
    role_raw = claims.get("role")
    role: str = role_raw if isinstance(role_raw, str) and role_raw else "operator"

    # Cache decoded claims for require_scope compatibility.
    request.state.jwt_claims = claims

    return TenantContext(org_id=org_id, user_id=sub, role=role)
