"""Unit tests for scripts/seed_sample_data.py.

Tests validate the seeding script's output structure, data types, FK
relationships, and PII-like column presence without requiring a live database.

Task: P18-T18.3 — End-to-End Validation with Sample Data
CONSTITUTION Priority 0: All data is generated by Faker (fictional, no real PII).
"""

from __future__ import annotations

import builtins
import csv
import re
import sys
from pathlib import Path
from typing import Any, ClassVar
from unittest.mock import MagicMock, patch

import pytest

# ---------------------------------------------------------------------------
# Helpers — resolve scripts/ path without importing the module directly
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = REPO_ROOT / "scripts"
SAMPLE_DATA_DIR = REPO_ROOT / "sample_data"


def _import_seed_module() -> Any:
    """Dynamically import seed_sample_data from scripts/ directory.

    Returns:
        The imported module object.
    """
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "seed_sample_data",
        SCRIPTS_DIR / "seed_sample_data.py",
    )
    assert spec is not None, "Could not locate scripts/seed_sample_data.py"
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)  # type: ignore[union-attr]
    return module


# ---------------------------------------------------------------------------
# Script existence
# ---------------------------------------------------------------------------


class TestScriptExists:
    """Verify the seeding script exists in the correct location."""

    def test_seed_sample_data_script_exists(self) -> None:
        """scripts/seed_sample_data.py must exist."""
        assert (SCRIPTS_DIR / "seed_sample_data.py").is_file(), (
            "scripts/seed_sample_data.py not found"
        )

    def test_script_not_in_src(self) -> None:
        """Seeding script must NOT be placed under src/."""
        src_dir = REPO_ROOT / "src"
        for py_file in src_dir.rglob("seed_sample_data.py"):
            pytest.fail(f"seed_sample_data.py found under src/: {py_file}")

    def test_sample_data_directory_exists(self) -> None:
        """sample_data/ directory must exist at repo root."""
        assert SAMPLE_DATA_DIR.is_dir(), "sample_data/ directory not found"

    def test_sample_data_not_gitignored(self) -> None:
        """sample_data/ must NOT appear in .gitignore (fictional data, safe to commit)."""
        gitignore = REPO_ROOT / ".gitignore"
        content = gitignore.read_text(encoding="utf-8")
        lines = [line.strip() for line in content.splitlines()]
        assert "sample_data/" not in lines, (
            "sample_data/ is listed in .gitignore but should be committed (fictional data)"
        )
        assert "sample_data" not in lines, (
            "sample_data is listed in .gitignore but should be committed (fictional data)"
        )


# ---------------------------------------------------------------------------
# CSV exports exist and have expected columns
# ---------------------------------------------------------------------------


class TestCsvExports:
    """Validate the CSV exports committed to sample_data/."""

    EXPECTED_FILES: ClassVar[dict[str, list[str]]] = {
        "customers.csv": [
            "id",
            "first_name",
            "last_name",
            "email",
            "ssn",
            "phone",
            "address",
            "created_at",
        ],
        "orders.csv": [
            "id",
            "customer_id",
            "order_date",
            "total_amount",
            "status",
        ],
        "order_items.csv": [
            "id",
            "order_id",
            "product_name",
            "quantity",
            "unit_price",
        ],
        "payments.csv": [
            "id",
            "order_id",
            "payment_date",
            "amount",
            "payment_method",
        ],
    }

    @pytest.mark.parametrize("filename", list(EXPECTED_FILES.keys()))
    def test_csv_file_exists(self, filename: str) -> None:
        """Each expected CSV file must exist in sample_data/."""
        assert (SAMPLE_DATA_DIR / filename).is_file(), f"sample_data/{filename} not found"

    @pytest.mark.parametrize(("filename", "expected_cols"), list(EXPECTED_FILES.items()))
    def test_csv_has_expected_columns(self, filename: str, expected_cols: list[str]) -> None:
        """Each CSV must have the correct header columns in exact order."""
        csv_path = SAMPLE_DATA_DIR / filename
        if not csv_path.is_file():
            pytest.skip(f"sample_data/{filename} not found — skipping column check")
        with csv_path.open(encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            assert reader.fieldnames is not None, f"{filename} has no header row"
            actual_cols = list(reader.fieldnames)
        assert actual_cols == expected_cols, (
            f"{filename}: expected columns {expected_cols}, got {actual_cols}"
        )

    @pytest.mark.parametrize("filename", list(EXPECTED_FILES.keys()))
    def test_csv_has_data_rows(self, filename: str) -> None:
        """Each CSV must contain at least one data row."""
        csv_path = SAMPLE_DATA_DIR / filename
        if not csv_path.is_file():
            pytest.skip(f"sample_data/{filename} not found")
        with csv_path.open(encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            rows = list(reader)
        assert len(rows) > 0, f"{filename} has no data rows"


# ---------------------------------------------------------------------------
# FK relationship integrity in the CSV data
# ---------------------------------------------------------------------------


class TestForeignKeyIntegrity:
    """Validate FK relationships across the CSV exports."""

    def _load_csv(self, filename: str) -> list[dict[str, str]]:
        """Load a CSV file from sample_data/ into a list of dicts."""
        csv_path = SAMPLE_DATA_DIR / filename
        if not csv_path.is_file():
            pytest.skip(f"sample_data/{filename} not found")
        with csv_path.open(encoding="utf-8", newline="") as f:
            return list(csv.DictReader(f))

    def test_orders_customer_id_references_customers(self) -> None:
        """Every orders.customer_id must reference an existing customers.id."""
        customers = self._load_csv("customers.csv")
        orders = self._load_csv("orders.csv")
        customer_ids = {row["id"] for row in customers}
        for row in orders:
            assert row["customer_id"] in customer_ids, (
                f"orders row {row['id']}: customer_id={row['customer_id']} not in customers table"
            )

    def test_order_items_order_id_references_orders(self) -> None:
        """Every order_items.order_id must reference an existing orders.id."""
        orders = self._load_csv("orders.csv")
        order_items = self._load_csv("order_items.csv")
        order_ids = {row["id"] for row in orders}
        for row in order_items:
            assert row["order_id"] in order_ids, (
                f"order_items row {row['id']}: order_id={row['order_id']} not in orders table"
            )

    def test_payments_order_id_references_orders(self) -> None:
        """Every payments.order_id must reference an existing orders.id."""
        orders = self._load_csv("orders.csv")
        payments = self._load_csv("payments.csv")
        order_ids = {row["id"] for row in orders}
        for row in payments:
            assert row["order_id"] in order_ids, (
                f"payments row {row['id']}: order_id={row['order_id']} not in orders table"
            )


# ---------------------------------------------------------------------------
# Data type validation in CSV exports
# ---------------------------------------------------------------------------


class TestCsvDataTypes:
    """Validate data types and formats in CSV exports."""

    def _load_csv(self, filename: str) -> list[dict[str, str]]:
        """Load a CSV from sample_data/."""
        csv_path = SAMPLE_DATA_DIR / filename
        if not csv_path.is_file():
            pytest.skip(f"sample_data/{filename} not found")
        with csv_path.open(encoding="utf-8", newline="") as f:
            return list(csv.DictReader(f))

    def test_customers_email_contains_at_symbol(self) -> None:
        """Customer emails must contain '@' (PII-like format)."""
        rows = self._load_csv("customers.csv")
        for row in rows:
            assert "@" in row["email"], (
                f"customers row {row['id']}: email={row['email']} is not email-shaped"
            )

    def test_customers_ssn_format(self) -> None:
        """Customer SSNs must match the ###-##-#### pattern (PII-like column present)."""
        ssn_pattern = re.compile(r"^\d{3}-\d{2}-\d{4}$")
        rows = self._load_csv("customers.csv")
        for row in rows:
            assert ssn_pattern.match(row["ssn"]), (
                f"customers row {row['id']}: ssn={row['ssn']!r} does not match ###-##-#### format"
            )

    def test_customers_phone_non_empty(self) -> None:
        """Customer phone numbers must be non-empty."""
        rows = self._load_csv("customers.csv")
        for row in rows:
            assert row["phone"].strip() != "", f"customers row {row['id']}: phone is empty"

    def test_orders_total_amount_is_numeric(self) -> None:
        """orders.total_amount must be parseable as a float."""
        rows = self._load_csv("orders.csv")
        for row in rows:
            try:
                float(row["total_amount"])
            except ValueError:
                pytest.fail(
                    f"orders row {row['id']}: total_amount={row['total_amount']} is not numeric"
                )

    def test_orders_status_is_valid(self) -> None:
        """orders.status must be one of the expected status values."""
        valid_statuses = {"pending", "processing", "shipped", "delivered", "cancelled"}
        rows = self._load_csv("orders.csv")
        for row in rows:
            assert row["status"] in valid_statuses, (
                f"orders row {row['id']}: status={row['status']} not in {valid_statuses}"
            )

    def test_order_items_quantity_is_positive_integer(self) -> None:
        """order_items.quantity must be a positive integer."""
        rows = self._load_csv("order_items.csv")
        for row in rows:
            try:
                qty = int(row["quantity"])
            except ValueError:
                pytest.fail(
                    f"order_items row {row['id']}: quantity={row['quantity']} is not an integer"
                )
            assert qty > 0, f"order_items row {row['id']}: quantity={qty} is not positive"

    def test_payments_amount_is_numeric(self) -> None:
        """payments.amount must be parseable as a float."""
        rows = self._load_csv("payments.csv")
        for row in rows:
            try:
                float(row["amount"])
            except ValueError:
                pytest.fail(f"payments row {row['id']}: amount={row['amount']} is not numeric")

    def test_payments_method_is_valid(self) -> None:
        """payments.payment_method must be one of the expected values."""
        valid_methods = {"credit_card", "debit_card", "bank_transfer", "paypal", "cash"}
        rows = self._load_csv("payments.csv")
        for row in rows:
            assert row["payment_method"] in valid_methods, (
                f"payments row {row['id']}: payment_method={row['payment_method']} "
                f"not in {valid_methods}"
            )


# ---------------------------------------------------------------------------
# Script module API tests (without requiring live DB)
# ---------------------------------------------------------------------------


class TestSeedModuleApi:
    """Test the public API of seed_sample_data module."""

    def test_module_has_generate_customers_function(self) -> None:
        """Module must expose a generate_customers function."""
        mod = _import_seed_module()
        assert hasattr(mod, "generate_customers"), (
            "seed_sample_data.py must define generate_customers()"
        )

    def test_module_has_generate_orders_function(self) -> None:
        """Module must expose a generate_orders function."""
        mod = _import_seed_module()
        assert hasattr(mod, "generate_orders"), "seed_sample_data.py must define generate_orders()"

    def test_module_has_generate_order_items_function(self) -> None:
        """Module must expose a generate_order_items function."""
        mod = _import_seed_module()
        assert hasattr(mod, "generate_order_items"), (
            "seed_sample_data.py must define generate_order_items()"
        )

    def test_module_has_generate_payments_function(self) -> None:
        """Module must expose a generate_payments function."""
        mod = _import_seed_module()
        assert hasattr(mod, "generate_payments"), (
            "seed_sample_data.py must define generate_payments()"
        )

    def test_generate_customers_returns_list_of_dicts(self) -> None:
        """generate_customers(n) must return a list of dicts with expected keys."""
        mod = _import_seed_module()
        result = mod.generate_customers(n=3, seed=42)
        assert isinstance(result, list), "generate_customers must return a list"
        assert len(result) == 3
        expected_keys = {
            "id",
            "first_name",
            "last_name",
            "email",
            "ssn",
            "phone",
            "address",
            "created_at",
        }
        for row in result:
            assert isinstance(row, dict)
            assert set(row.keys()) == expected_keys, (
                f"generate_customers row missing keys: {expected_keys - set(row.keys())}"
            )

    def test_generate_orders_fk_references_customers(self) -> None:
        """generate_orders must reference customer IDs from the provided customers list."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=3, seed=42)
        orders = mod.generate_orders(customers=customers, n=5, seed=42)
        customer_ids = {c["id"] for c in customers}
        for order in orders:
            assert order["customer_id"] in customer_ids, (
                f"order {order['id']}: customer_id={order['customer_id']} not in provided customers"
            )

    def test_generate_order_items_fk_references_orders(self) -> None:
        """generate_order_items must reference order IDs from the provided orders list."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=3, seed=42)
        orders = mod.generate_orders(customers=customers, n=5, seed=42)
        items = mod.generate_order_items(orders=orders, n=10, seed=42)
        order_ids = {o["id"] for o in orders}
        for item in items:
            assert item["order_id"] in order_ids, (
                f"order_item {item['id']}: order_id={item['order_id']} not in provided orders"
            )

    def test_generate_payments_fk_references_orders(self) -> None:
        """generate_payments must reference order IDs from the provided orders list."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=3, seed=42)
        orders = mod.generate_orders(customers=customers, n=5, seed=42)
        payments = mod.generate_payments(orders=orders, n=5, seed=42)
        order_ids = {o["id"] for o in orders}
        for payment in payments:
            assert payment["order_id"] in order_ids, (
                f"payment {payment['id']}: order_id={payment['order_id']} not in provided orders"
            )

    def test_generate_customers_is_deterministic(self) -> None:
        """generate_customers with the same seed must produce identical output."""
        mod = _import_seed_module()
        first = mod.generate_customers(n=5, seed=99)
        second = mod.generate_customers(n=5, seed=99)
        assert first == second, (
            "generate_customers is not deterministic — same seed produced different output"
        )

    def test_generate_customers_different_seeds_differ(self) -> None:
        """generate_customers with different seeds must produce different output."""
        mod = _import_seed_module()
        first = mod.generate_customers(n=5, seed=1)
        second = mod.generate_customers(n=5, seed=2)
        assert first != second, "generate_customers with different seeds produced identical output"

    def test_module_has_ddl_function(self) -> None:
        """Module must expose a build_ddl function for schema generation."""
        mod = _import_seed_module()
        assert hasattr(mod, "build_ddl"), "seed_sample_data.py must define build_ddl()"

    def test_build_ddl_contains_all_tables(self) -> None:
        """build_ddl() must return DDL containing all four table definitions."""
        mod = _import_seed_module()
        ddl = mod.build_ddl()
        assert isinstance(ddl, str)
        for table in ("customers", "orders", "order_items", "payments"):
            assert table in ddl.lower(), f"build_ddl() output missing CREATE TABLE for {table}"

    def test_build_ddl_contains_foreign_keys(self) -> None:
        """build_ddl() must include REFERENCES clauses for FK relationships."""
        mod = _import_seed_module()
        ddl = mod.build_ddl()
        assert "REFERENCES" in ddl.upper(), (
            "build_ddl() output has no FOREIGN KEY REFERENCES clauses"
        )

    def test_module_has_export_csv_function(self) -> None:
        """Module must expose an export_csv function."""
        mod = _import_seed_module()
        assert hasattr(mod, "export_csv"), "seed_sample_data.py must define export_csv()"

    def test_export_csv_produces_valid_csv(self, tmp_path: Path) -> None:
        """export_csv must write a valid CSV file with correct headers."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=2, seed=42)
        out_file = tmp_path / "test_customers.csv"
        mod.export_csv(rows=customers, path=out_file)
        assert out_file.is_file()
        with out_file.open(encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            rows = list(reader)
        assert len(rows) == 2
        assert "email" in (reader.fieldnames or [])

    def test_export_csv_exact_column_names_customers(self, tmp_path: Path) -> None:
        """export_csv with table='customers' must write exactly the canonical column names."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=2, seed=42)
        out_file = tmp_path / "customers.csv"
        mod.export_csv(rows=customers, path=out_file, table="customers")
        with out_file.open(encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            list(reader)  # consume rows so fieldnames is populated
            actual_cols = list(reader.fieldnames or [])
        expected_cols = [
            "id",
            "first_name",
            "last_name",
            "email",
            "ssn",
            "phone",
            "address",
            "created_at",
        ]
        assert actual_cols == expected_cols, (
            f"export_csv(table='customers') columns mismatch: "
            f"expected {expected_cols}, got {actual_cols}"
        )

    def test_export_csv_exact_column_names_payments(self, tmp_path: Path) -> None:
        """export_csv with table='payments' must write exactly the canonical column names."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=2, seed=42)
        orders = mod.generate_orders(customers=customers, n=3, seed=42)
        payments = mod.generate_payments(orders=orders, seed=42)
        out_file = tmp_path / "payments.csv"
        mod.export_csv(rows=payments, path=out_file, table="payments")
        with out_file.open(encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            list(reader)
            actual_cols = list(reader.fieldnames or [])
        expected_cols = ["id", "order_id", "payment_date", "amount", "payment_method"]
        assert actual_cols == expected_cols, (
            f"export_csv(table='payments') columns mismatch: "
            f"expected {expected_cols}, got {actual_cols}"
        )

    def test_export_csv_empty_rows_returns_without_writing(self, tmp_path: Path) -> None:
        """export_csv with empty rows list must return early without creating a file."""
        mod = _import_seed_module()
        out_file = tmp_path / "empty.csv"
        mod.export_csv(rows=[], path=out_file)
        # The function logs a warning and returns — no file should be written
        assert not out_file.exists(), (
            "export_csv wrote a file for an empty rows list — should return early"
        )

    def test_export_csv_unknown_table_falls_through_to_dict_keys(self, tmp_path: Path) -> None:
        """export_csv with an unknown table name falls through to row dict key order."""
        mod = _import_seed_module()
        rows: list[dict[str, Any]] = [{"alpha": "1", "beta": "2"}]
        out_file = tmp_path / "unknown.csv"
        mod.export_csv(rows=rows, path=out_file, table="nonexistent_table")
        assert out_file.is_file(), "export_csv did not write a file for unknown table name"
        with out_file.open(encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            data = list(reader)
            actual_cols = list(reader.fieldnames or [])
        assert actual_cols == ["alpha", "beta"], (
            f"export_csv with unknown table should use row key order, got: {actual_cols}"
        )
        assert len(data) == 1

    def test_module_has_cli_entrypoint(self) -> None:
        """Module must have a Click CLI or argparse main entrypoint."""
        mod = _import_seed_module()
        # Accept either a click command or a __main__ block
        has_cli = hasattr(mod, "main") or hasattr(mod, "cli")
        assert has_cli, "seed_sample_data.py must define a CLI entrypoint (main or cli)"


# ---------------------------------------------------------------------------
# FINDING 2/3 — Edge-case and empty-input tests
# ---------------------------------------------------------------------------


class TestEdgeCases:
    """Edge-case coverage: empty inputs, None paths, default/CLI paths."""

    def test_generate_payments_none_path_returns_one_per_order(self) -> None:
        """generate_payments(orders, n=None) must return exactly one payment per order."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=3, seed=42)
        orders = mod.generate_orders(customers=customers, n=5, seed=42)
        payments = mod.generate_payments(orders=orders, seed=42)  # n=None — CLI default
        assert len(payments) == len(orders), (
            f"generate_payments(n=None) returned {len(payments)} payments "
            f"for {len(orders)} orders; expected exactly one per order"
        )

    def test_generate_payments_none_path_order_ids_match(self) -> None:
        """generate_payments(n=None) payment order_ids must follow sequential order-per-order."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=2, seed=42)
        orders = mod.generate_orders(customers=customers, n=4, seed=42)
        payments = mod.generate_payments(orders=orders, seed=42)
        order_ids_from_orders = [o["id"] for o in orders]
        order_ids_from_payments = [p["order_id"] for p in payments]
        assert order_ids_from_payments == order_ids_from_orders, (
            "generate_payments(n=None) must assign one payment per order in sequence"
        )

    def test_generate_orders_empty_customers_n_zero(self) -> None:
        """generate_orders([], n=0) must return an empty list."""
        mod = _import_seed_module()
        result = mod.generate_orders(customers=[], n=0, seed=42)
        assert result == [], f"generate_orders([], n=0) returned {result!r}, expected []"

    def test_generate_order_items_empty_orders_n_zero(self) -> None:
        """generate_order_items([], n=0) must return an empty list."""
        mod = _import_seed_module()
        result = mod.generate_order_items(orders=[], n=0, seed=42)
        assert result == [], f"generate_order_items([], n=0) returned {result!r}, expected []"

    def test_generate_order_items_empty_orders_n_none(self) -> None:
        """generate_order_items([], n=None) must return an empty list."""
        mod = _import_seed_module()
        result = mod.generate_order_items(orders=[], n=None, seed=42)
        assert result == [], f"generate_order_items([], n=None) returned {result!r}, expected []"

    def test_generate_payments_empty_orders_n_zero(self) -> None:
        """generate_payments([], n=0) must return an empty list."""
        mod = _import_seed_module()
        result = mod.generate_payments(orders=[], n=0, seed=42)
        assert result == [], f"generate_payments([], n=0) returned {result!r}, expected []"

    def test_generate_payments_empty_orders_n_none(self) -> None:
        """generate_payments([], n=None) must return an empty list."""
        mod = _import_seed_module()
        result = mod.generate_payments(orders=[], seed=42)  # n=None default
        assert result == [], f"generate_payments([], n=None) returned {result!r}, expected []"


# ---------------------------------------------------------------------------
# FINDING 3 — Error-path tests: ImportError and SystemExit for _execute_against_db
# ---------------------------------------------------------------------------


class TestExecuteAgainstDbErrorPaths:
    """Test error paths in _execute_against_db without a live database."""

    def test_execute_against_db_sysexit_on_import_error(self) -> None:
        """_execute_against_db must call sys.exit(1) when psycopg2 cannot be imported."""
        mod = _import_seed_module()

        real_import = builtins.__import__

        def mock_import(name: str, *args: Any, **kwargs: Any) -> Any:
            if name == "psycopg2":
                raise ImportError("psycopg2 not available")
            return real_import(name, *args, **kwargs)

        with patch.object(builtins, "__import__", side_effect=mock_import):
            with pytest.raises(SystemExit) as exc_info:
                mod._execute_against_db(
                    dsn="postgresql://localhost/test",
                    ddl="",
                    tables={},
                )
        assert exc_info.value.code == 1, (
            f"_execute_against_db should exit with code 1 on ImportError, got {exc_info.value.code}"
        )

    def test_execute_against_db_raises_on_db_failure(self) -> None:
        """_execute_against_db must re-raise the database error after rollback."""
        mod = _import_seed_module()

        mock_psycopg2 = MagicMock()
        db_error = Exception("connection refused")
        mock_psycopg2.Error = Exception  # treat all exceptions as psycopg2.Error
        mock_psycopg2.connect.side_effect = db_error

        with patch.dict(sys.modules, {"psycopg2": mock_psycopg2}):
            with pytest.raises(Exception, match="connection refused"):
                mod._execute_against_db(
                    dsn="postgresql://localhost/test",
                    ddl="CREATE TABLE foo (id INT)",
                    tables={},
                )

    def test_execute_against_db_rolls_back_on_cursor_error(self) -> None:
        """_execute_against_db must rollback the transaction on cursor execution failure."""
        mod = _import_seed_module()

        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_cursor.__enter__ = MagicMock(return_value=mock_cursor)
        mock_cursor.__exit__ = MagicMock(return_value=False)
        mock_cursor.execute.side_effect = Exception("syntax error")
        mock_conn.cursor.return_value = mock_cursor

        mock_psycopg2 = MagicMock()
        mock_psycopg2.Error = Exception
        mock_psycopg2.connect.return_value = mock_conn

        with patch.dict(sys.modules, {"psycopg2": mock_psycopg2}):
            with pytest.raises(Exception, match="syntax error"):
                mod._execute_against_db(
                    dsn="postgresql://localhost/test",
                    ddl="INVALID SQL",
                    tables={},
                )

        mock_conn.rollback.assert_called_once()
        mock_conn.close.assert_called_once()


# ---------------------------------------------------------------------------
# FINDING 4 — Determinism tests for generate_orders, generate_order_items,
#              generate_payments
# ---------------------------------------------------------------------------


class TestDeterminism:
    """Same seed must produce identical output for all generators."""

    def test_generate_orders_is_deterministic(self) -> None:
        """generate_orders with the same seed must produce identical output."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=5, seed=99)
        first = mod.generate_orders(customers=customers, n=10, seed=99)
        second = mod.generate_orders(customers=customers, n=10, seed=99)
        assert first == second, (
            "generate_orders is not deterministic — same seed produced different output"
        )

    def test_generate_orders_different_seeds_differ(self) -> None:
        """generate_orders with different seeds must produce different output."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=5, seed=1)
        first = mod.generate_orders(customers=customers, n=10, seed=1)
        second = mod.generate_orders(customers=customers, n=10, seed=2)
        assert first != second, "generate_orders with different seeds produced identical output"

    def test_generate_order_items_is_deterministic(self) -> None:
        """generate_order_items with the same seed must produce identical output."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=5, seed=99)
        orders = mod.generate_orders(customers=customers, n=10, seed=99)
        first = mod.generate_order_items(orders=orders, n=20, seed=99)
        second = mod.generate_order_items(orders=orders, n=20, seed=99)
        assert first == second, (
            "generate_order_items is not deterministic — same seed produced different output"
        )

    def test_generate_order_items_different_seeds_differ(self) -> None:
        """generate_order_items with different seeds must produce different output."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=5, seed=1)
        orders = mod.generate_orders(customers=customers, n=10, seed=1)
        first = mod.generate_order_items(orders=orders, n=20, seed=1)
        second = mod.generate_order_items(orders=orders, n=20, seed=2)
        assert first != second, (
            "generate_order_items with different seeds produced identical output"
        )

    def test_generate_payments_is_deterministic(self) -> None:
        """generate_payments with the same seed must produce identical output."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=5, seed=99)
        orders = mod.generate_orders(customers=customers, n=10, seed=99)
        first = mod.generate_payments(orders=orders, n=15, seed=99)
        second = mod.generate_payments(orders=orders, n=15, seed=99)
        assert first == second, (
            "generate_payments is not deterministic — same seed produced different output"
        )

    def test_generate_payments_none_path_is_deterministic(self) -> None:
        """generate_payments(n=None) with the same seed must produce identical output."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=5, seed=99)
        orders = mod.generate_orders(customers=customers, n=10, seed=99)
        first = mod.generate_payments(orders=orders, seed=99)
        second = mod.generate_payments(orders=orders, seed=99)
        assert first == second, (
            "generate_payments(n=None) is not deterministic — same seed produced different output"
        )

    def test_generate_payments_different_seeds_differ(self) -> None:
        """generate_payments with different seeds must produce different output."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=5, seed=1)
        orders = mod.generate_orders(customers=customers, n=10, seed=1)
        first = mod.generate_payments(orders=orders, n=15, seed=1)
        second = mod.generate_payments(orders=orders, n=15, seed=2)
        assert first != second, "generate_payments with different seeds produced identical output"


# ---------------------------------------------------------------------------
# E2E_VALIDATION.md existence
# ---------------------------------------------------------------------------


class TestE2eValidationDoc:
    """Validate that the E2E validation documentation exists."""

    def test_e2e_validation_doc_exists(self) -> None:
        """docs/E2E_VALIDATION.md must exist."""
        doc_path = REPO_ROOT / "docs" / "E2E_VALIDATION.md"
        assert doc_path.is_file(), "docs/E2E_VALIDATION.md not found"

    def test_e2e_doc_contains_docker_compose_step(self) -> None:
        """docs/E2E_VALIDATION.md must document the Docker infrastructure step.

        Updated for P28: the document was rewritten to reflect the new container-based
        validation approach (conclave-app-e2e). The old docker-compose CLI workflow
        was superseded; the test now checks for Docker infrastructure evidence that
        IS present in the P28 document.
        """
        doc_path = REPO_ROOT / "docs" / "E2E_VALIDATION.md"
        if not doc_path.is_file():
            pytest.skip("docs/E2E_VALIDATION.md not found")
        content = doc_path.read_text(encoding="utf-8")
        assert "docker" in content.lower(), "E2E_VALIDATION.md must document Docker infrastructure"
        assert "conclave-app-e2e" in content, (
            "E2E_VALIDATION.md must reference the conclave-app-e2e container"
        )

    def test_e2e_doc_contains_seed_data_step(self) -> None:
        """docs/E2E_VALIDATION.md must document the infrastructure health step.

        Updated for P28: the old seed-data CLI step was superseded by a live
        container health validation step. The test now checks for Infrastructure
        Health evidence that IS present in the P28 document.
        """
        doc_path = REPO_ROOT / "docs" / "E2E_VALIDATION.md"
        if not doc_path.is_file():
            pytest.skip("docs/E2E_VALIDATION.md not found")
        content = doc_path.read_text(encoding="utf-8")
        assert "Infrastructure Health" in content, (
            "E2E_VALIDATION.md must document the infrastructure health step"
        )

    def test_e2e_doc_contains_conclave_subset_step(self) -> None:
        """docs/E2E_VALIDATION.md must document the API pipeline step.

        Updated for P28: the old conclave-subset CLI step was superseded by a live
        API pipeline validation step with HTTP evidence. The test now checks for
        API Pipeline content that IS present in the P28 document.
        """
        doc_path = REPO_ROOT / "docs" / "E2E_VALIDATION.md"
        if not doc_path.is_file():
            pytest.skip("docs/E2E_VALIDATION.md not found")
        content = doc_path.read_text(encoding="utf-8")
        assert "API Pipeline" in content, "E2E_VALIDATION.md must document the API pipeline step"
        assert "HTTP/1.1" in content, "E2E_VALIDATION.md must contain live HTTP response evidence"

    def test_e2e_doc_contains_synthesis_step(self) -> None:
        """docs/E2E_VALIDATION.md must document the synthesis API step."""
        doc_path = REPO_ROOT / "docs" / "E2E_VALIDATION.md"
        if not doc_path.is_file():
            pytest.skip("docs/E2E_VALIDATION.md not found")
        content = doc_path.read_text(encoding="utf-8").lower()
        assert "synth" in content, "E2E_VALIDATION.md must document the synthesis step"

    def test_e2e_doc_contains_live_validation_evidence(self) -> None:
        """docs/E2E_VALIDATION.md must contain live validation evidence (P28).

        P28 rewrote the E2E document with fresh live evidence: HTTP API responses,
        Playwright screenshot run output, Dockerfile findings, and quality gate
        results. This test verifies the P28 live run evidence is present.
        """
        doc_path = REPO_ROOT / "docs" / "E2E_VALIDATION.md"
        if not doc_path.is_file():
            pytest.skip("docs/E2E_VALIDATION.md not found")
        content = doc_path.read_text(encoding="utf-8")
        # P28 documents blocking findings in the Findings Summary table
        assert "BLOCKER" in content, (
            "E2E_VALIDATION.md must document findings from the live validation run"
        )
        # P28 Playwright evidence: 32 specs passing (4 pre-existing unseal.spec.ts failures)
        assert "32 passed" in content, "E2E_VALIDATION.md must contain Playwright test run evidence"
        # P28 live API evidence: HTTP responses captured
        assert "HTTP/1.1 200" in content, (
            "E2E_VALIDATION.md must contain live HTTP response evidence"
        )
