"""Unit tests for scripts/seed_sample_data.py.

Tests validate the seeding script's output structure, data types, FK
relationships, and PII-like column presence without requiring a live database.

Task: P18-T18.3 — End-to-End Validation with Sample Data
CONSTITUTION Priority 0: All data is generated by Faker (fictional, no real PII).
"""

from __future__ import annotations

import csv
import io
import sys
from pathlib import Path
from typing import Any
from unittest.mock import MagicMock, patch

import pytest

# ---------------------------------------------------------------------------
# Helpers — resolve scripts/ path without importing the module directly
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = REPO_ROOT / "scripts"
SAMPLE_DATA_DIR = REPO_ROOT / "sample_data"


def _import_seed_module() -> Any:
    """Dynamically import seed_sample_data from scripts/ directory.

    Returns:
        The imported module object.
    """
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "seed_sample_data",
        SCRIPTS_DIR / "seed_sample_data.py",
    )
    assert spec is not None, "Could not locate scripts/seed_sample_data.py"
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)  # type: ignore[union-attr]
    return module


# ---------------------------------------------------------------------------
# Script existence
# ---------------------------------------------------------------------------


class TestScriptExists:
    """Verify the seeding script exists in the correct location."""

    def test_seed_sample_data_script_exists(self) -> None:
        """scripts/seed_sample_data.py must exist."""
        assert (SCRIPTS_DIR / "seed_sample_data.py").is_file(), (
            "scripts/seed_sample_data.py not found"
        )

    def test_script_not_in_src(self) -> None:
        """Seeding script must NOT be placed under src/."""
        src_dir = REPO_ROOT / "src"
        for py_file in src_dir.rglob("seed_sample_data.py"):
            pytest.fail(f"seed_sample_data.py found under src/: {py_file}")

    def test_sample_data_directory_exists(self) -> None:
        """sample_data/ directory must exist at repo root."""
        assert SAMPLE_DATA_DIR.is_dir(), "sample_data/ directory not found"

    def test_sample_data_not_gitignored(self) -> None:
        """sample_data/ must NOT appear in .gitignore (fictional data, safe to commit)."""
        gitignore = REPO_ROOT / ".gitignore"
        content = gitignore.read_text(encoding="utf-8")
        lines = [line.strip() for line in content.splitlines()]
        assert "sample_data/" not in lines, (
            "sample_data/ is listed in .gitignore but should be committed (fictional data)"
        )
        assert "sample_data" not in lines, (
            "sample_data is listed in .gitignore but should be committed (fictional data)"
        )


# ---------------------------------------------------------------------------
# CSV exports exist and have expected columns
# ---------------------------------------------------------------------------


class TestCsvExports:
    """Validate the CSV exports committed to sample_data/."""

    EXPECTED_FILES: dict[str, list[str]] = {
        "customers.csv": [
            "id",
            "first_name",
            "last_name",
            "email",
            "ssn",
            "phone",
            "address",
            "created_at",
        ],
        "orders.csv": [
            "id",
            "customer_id",
            "order_date",
            "total_amount",
            "status",
        ],
        "order_items.csv": [
            "id",
            "order_id",
            "product_name",
            "quantity",
            "unit_price",
        ],
        "payments.csv": [
            "id",
            "order_id",
            "payment_date",
            "amount",
            "payment_method",
        ],
    }

    @pytest.mark.parametrize("filename", list(EXPECTED_FILES.keys()))
    def test_csv_file_exists(self, filename: str) -> None:
        """Each expected CSV file must exist in sample_data/."""
        assert (SAMPLE_DATA_DIR / filename).is_file(), (
            f"sample_data/{filename} not found"
        )

    @pytest.mark.parametrize("filename,expected_cols", list(EXPECTED_FILES.items()))
    def test_csv_has_expected_columns(
        self, filename: str, expected_cols: list[str]
    ) -> None:
        """Each CSV must have the correct header columns in exact order."""
        csv_path = SAMPLE_DATA_DIR / filename
        if not csv_path.is_file():
            pytest.skip(f"sample_data/{filename} not found — skipping column check")
        with csv_path.open(encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            assert reader.fieldnames is not None, f"{filename} has no header row"
            actual_cols = list(reader.fieldnames)
        assert actual_cols == expected_cols, (
            f"{filename}: expected columns {expected_cols}, got {actual_cols}"
        )

    @pytest.mark.parametrize("filename", list(EXPECTED_FILES.keys()))
    def test_csv_has_data_rows(self, filename: str) -> None:
        """Each CSV must contain at least one data row."""
        csv_path = SAMPLE_DATA_DIR / filename
        if not csv_path.is_file():
            pytest.skip(f"sample_data/{filename} not found")
        with csv_path.open(encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            rows = list(reader)
        assert len(rows) > 0, f"{filename} has no data rows"


# ---------------------------------------------------------------------------
# FK relationship integrity in the CSV data
# ---------------------------------------------------------------------------


class TestForeignKeyIntegrity:
    """Validate FK relationships across the CSV exports."""

    def _load_csv(self, filename: str) -> list[dict[str, str]]:
        """Load a CSV file from sample_data/ into a list of dicts."""
        csv_path = SAMPLE_DATA_DIR / filename
        if not csv_path.is_file():
            pytest.skip(f"sample_data/{filename} not found")
        with csv_path.open(encoding="utf-8", newline="") as f:
            return list(csv.DictReader(f))

    def test_orders_customer_id_references_customers(self) -> None:
        """Every orders.customer_id must reference an existing customers.id."""
        customers = self._load_csv("customers.csv")
        orders = self._load_csv("orders.csv")
        customer_ids = {row["id"] for row in customers}
        for row in orders:
            assert row["customer_id"] in customer_ids, (
                f"orders row {row['id']}: customer_id={row['customer_id']} "
                f"not in customers table"
            )

    def test_order_items_order_id_references_orders(self) -> None:
        """Every order_items.order_id must reference an existing orders.id."""
        orders = self._load_csv("orders.csv")
        order_items = self._load_csv("order_items.csv")
        order_ids = {row["id"] for row in orders}
        for row in order_items:
            assert row["order_id"] in order_ids, (
                f"order_items row {row['id']}: order_id={row['order_id']} "
                f"not in orders table"
            )

    def test_payments_order_id_references_orders(self) -> None:
        """Every payments.order_id must reference an existing orders.id."""
        orders = self._load_csv("orders.csv")
        payments = self._load_csv("payments.csv")
        order_ids = {row["id"] for row in orders}
        for row in payments:
            assert row["order_id"] in order_ids, (
                f"payments row {row['id']}: order_id={row['order_id']} "
                f"not in orders table"
            )


# ---------------------------------------------------------------------------
# Data type validation in CSV exports
# ---------------------------------------------------------------------------


class TestCsvDataTypes:
    """Validate data types and formats in CSV exports."""

    def _load_csv(self, filename: str) -> list[dict[str, str]]:
        """Load a CSV from sample_data/."""
        csv_path = SAMPLE_DATA_DIR / filename
        if not csv_path.is_file():
            pytest.skip(f"sample_data/{filename} not found")
        with csv_path.open(encoding="utf-8", newline="") as f:
            return list(csv.DictReader(f))

    def test_customers_email_contains_at_symbol(self) -> None:
        """Customer emails must contain '@' (PII-like format)."""
        rows = self._load_csv("customers.csv")
        for row in rows:
            assert "@" in row["email"], (
                f"customers row {row['id']}: email={row['email']} is not email-shaped"
            )

    def test_customers_ssn_format(self) -> None:
        """Customer SSNs must be non-empty strings (PII-like column present)."""
        rows = self._load_csv("customers.csv")
        for row in rows:
            assert row["ssn"].strip() != "", (
                f"customers row {row['id']}: ssn is empty"
            )

    def test_customers_phone_non_empty(self) -> None:
        """Customer phone numbers must be non-empty."""
        rows = self._load_csv("customers.csv")
        for row in rows:
            assert row["phone"].strip() != "", (
                f"customers row {row['id']}: phone is empty"
            )

    def test_orders_total_amount_is_numeric(self) -> None:
        """orders.total_amount must be parseable as a float."""
        rows = self._load_csv("orders.csv")
        for row in rows:
            try:
                float(row["total_amount"])
            except ValueError:
                pytest.fail(
                    f"orders row {row['id']}: total_amount={row['total_amount']} "
                    f"is not numeric"
                )

    def test_orders_status_is_valid(self) -> None:
        """orders.status must be one of the expected status values."""
        valid_statuses = {"pending", "processing", "shipped", "delivered", "cancelled"}
        rows = self._load_csv("orders.csv")
        for row in rows:
            assert row["status"] in valid_statuses, (
                f"orders row {row['id']}: status={row['status']} "
                f"not in {valid_statuses}"
            )

    def test_order_items_quantity_is_positive_integer(self) -> None:
        """order_items.quantity must be a positive integer."""
        rows = self._load_csv("order_items.csv")
        for row in rows:
            try:
                qty = int(row["quantity"])
            except ValueError:
                pytest.fail(
                    f"order_items row {row['id']}: quantity={row['quantity']} "
                    f"is not an integer"
                )
            assert qty > 0, (
                f"order_items row {row['id']}: quantity={qty} is not positive"
            )

    def test_payments_amount_is_numeric(self) -> None:
        """payments.amount must be parseable as a float."""
        rows = self._load_csv("payments.csv")
        for row in rows:
            try:
                float(row["amount"])
            except ValueError:
                pytest.fail(
                    f"payments row {row['id']}: amount={row['amount']} "
                    f"is not numeric"
                )

    def test_payments_method_is_valid(self) -> None:
        """payments.payment_method must be one of the expected values."""
        valid_methods = {"credit_card", "debit_card", "bank_transfer", "paypal", "cash"}
        rows = self._load_csv("payments.csv")
        for row in rows:
            assert row["payment_method"] in valid_methods, (
                f"payments row {row['id']}: payment_method={row['payment_method']} "
                f"not in {valid_methods}"
            )


# ---------------------------------------------------------------------------
# Script module API tests (without requiring live DB)
# ---------------------------------------------------------------------------


class TestSeedModuleApi:
    """Test the public API of seed_sample_data module."""

    def test_module_has_generate_customers_function(self) -> None:
        """Module must expose a generate_customers function."""
        mod = _import_seed_module()
        assert hasattr(mod, "generate_customers"), (
            "seed_sample_data.py must define generate_customers()"
        )

    def test_module_has_generate_orders_function(self) -> None:
        """Module must expose a generate_orders function."""
        mod = _import_seed_module()
        assert hasattr(mod, "generate_orders"), (
            "seed_sample_data.py must define generate_orders()"
        )

    def test_module_has_generate_order_items_function(self) -> None:
        """Module must expose a generate_order_items function."""
        mod = _import_seed_module()
        assert hasattr(mod, "generate_order_items"), (
            "seed_sample_data.py must define generate_order_items()"
        )

    def test_module_has_generate_payments_function(self) -> None:
        """Module must expose a generate_payments function."""
        mod = _import_seed_module()
        assert hasattr(mod, "generate_payments"), (
            "seed_sample_data.py must define generate_payments()"
        )

    def test_generate_customers_returns_list_of_dicts(self) -> None:
        """generate_customers(n) must return a list of dicts with expected keys."""
        mod = _import_seed_module()
        result = mod.generate_customers(n=3, seed=42)
        assert isinstance(result, list), "generate_customers must return a list"
        assert len(result) == 3
        expected_keys = {
            "id",
            "first_name",
            "last_name",
            "email",
            "ssn",
            "phone",
            "address",
            "created_at",
        }
        for row in result:
            assert isinstance(row, dict)
            assert set(row.keys()) == expected_keys, (
                f"generate_customers row missing keys: "
                f"{expected_keys - set(row.keys())}"
            )

    def test_generate_orders_fk_references_customers(self) -> None:
        """generate_orders must reference customer IDs from the provided customers list."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=3, seed=42)
        orders = mod.generate_orders(customers=customers, n=5, seed=42)
        customer_ids = {c["id"] for c in customers}
        for order in orders:
            assert order["customer_id"] in customer_ids, (
                f"order {order['id']}: customer_id={order['customer_id']} "
                f"not in provided customers"
            )

    def test_generate_order_items_fk_references_orders(self) -> None:
        """generate_order_items must reference order IDs from the provided orders list."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=3, seed=42)
        orders = mod.generate_orders(customers=customers, n=5, seed=42)
        items = mod.generate_order_items(orders=orders, n=10, seed=42)
        order_ids = {o["id"] for o in orders}
        for item in items:
            assert item["order_id"] in order_ids, (
                f"order_item {item['id']}: order_id={item['order_id']} "
                f"not in provided orders"
            )

    def test_generate_payments_fk_references_orders(self) -> None:
        """generate_payments must reference order IDs from the provided orders list."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=3, seed=42)
        orders = mod.generate_orders(customers=customers, n=5, seed=42)
        payments = mod.generate_payments(orders=orders, n=5, seed=42)
        order_ids = {o["id"] for o in orders}
        for payment in payments:
            assert payment["order_id"] in order_ids, (
                f"payment {payment['id']}: order_id={payment['order_id']} "
                f"not in provided orders"
            )

    def test_generate_customers_is_deterministic(self) -> None:
        """generate_customers with the same seed must produce identical output."""
        mod = _import_seed_module()
        first = mod.generate_customers(n=5, seed=99)
        second = mod.generate_customers(n=5, seed=99)
        assert first == second, (
            "generate_customers is not deterministic — same seed produced different output"
        )

    def test_generate_customers_different_seeds_differ(self) -> None:
        """generate_customers with different seeds must produce different output."""
        mod = _import_seed_module()
        first = mod.generate_customers(n=5, seed=1)
        second = mod.generate_customers(n=5, seed=2)
        assert first != second, (
            "generate_customers with different seeds produced identical output"
        )

    def test_module_has_ddl_function(self) -> None:
        """Module must expose a build_ddl function for schema generation."""
        mod = _import_seed_module()
        assert hasattr(mod, "build_ddl"), (
            "seed_sample_data.py must define build_ddl()"
        )

    def test_build_ddl_contains_all_tables(self) -> None:
        """build_ddl() must return DDL containing all four table definitions."""
        mod = _import_seed_module()
        ddl = mod.build_ddl()
        assert isinstance(ddl, str)
        for table in ("customers", "orders", "order_items", "payments"):
            assert table in ddl.lower(), (
                f"build_ddl() output missing CREATE TABLE for {table}"
            )

    def test_build_ddl_contains_foreign_keys(self) -> None:
        """build_ddl() must include REFERENCES clauses for FK relationships."""
        mod = _import_seed_module()
        ddl = mod.build_ddl()
        assert "REFERENCES" in ddl.upper(), (
            "build_ddl() output has no FOREIGN KEY REFERENCES clauses"
        )

    def test_module_has_export_csv_function(self) -> None:
        """Module must expose an export_csv function."""
        mod = _import_seed_module()
        assert hasattr(mod, "export_csv"), (
            "seed_sample_data.py must define export_csv()"
        )

    def test_export_csv_produces_valid_csv(self, tmp_path: Path) -> None:
        """export_csv must write a valid CSV file with correct headers."""
        mod = _import_seed_module()
        customers = mod.generate_customers(n=2, seed=42)
        out_file = tmp_path / "test_customers.csv"
        mod.export_csv(rows=customers, path=out_file)
        assert out_file.is_file()
        with out_file.open(encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            rows = list(reader)
        assert len(rows) == 2
        assert "email" in (reader.fieldnames or [])

    def test_module_has_cli_entrypoint(self) -> None:
        """Module must have a Click CLI or argparse main entrypoint."""
        mod = _import_seed_module()
        # Accept either a click command or a __main__ block
        has_cli = hasattr(mod, "main") or hasattr(mod, "cli")
        assert has_cli, (
            "seed_sample_data.py must define a CLI entrypoint (main or cli)"
        )


# ---------------------------------------------------------------------------
# E2E_VALIDATION.md existence
# ---------------------------------------------------------------------------


class TestE2eValidationDoc:
    """Validate that the E2E validation documentation exists."""

    def test_e2e_validation_doc_exists(self) -> None:
        """docs/E2E_VALIDATION.md must exist."""
        doc_path = REPO_ROOT / "docs" / "E2E_VALIDATION.md"
        assert doc_path.is_file(), "docs/E2E_VALIDATION.md not found"

    def test_e2e_doc_contains_docker_compose_step(self) -> None:
        """docs/E2E_VALIDATION.md must document the docker-compose step."""
        doc_path = REPO_ROOT / "docs" / "E2E_VALIDATION.md"
        if not doc_path.is_file():
            pytest.skip("docs/E2E_VALIDATION.md not found")
        content = doc_path.read_text(encoding="utf-8").lower()
        assert "docker-compose" in content or "docker compose" in content, (
            "E2E_VALIDATION.md must document docker-compose startup step"
        )

    def test_e2e_doc_contains_seed_data_step(self) -> None:
        """docs/E2E_VALIDATION.md must document the seed data step."""
        doc_path = REPO_ROOT / "docs" / "E2E_VALIDATION.md"
        if not doc_path.is_file():
            pytest.skip("docs/E2E_VALIDATION.md not found")
        content = doc_path.read_text(encoding="utf-8").lower()
        assert "seed" in content, (
            "E2E_VALIDATION.md must document the seeding step"
        )

    def test_e2e_doc_contains_conclave_subset_step(self) -> None:
        """docs/E2E_VALIDATION.md must document the conclave-subset CLI step."""
        doc_path = REPO_ROOT / "docs" / "E2E_VALIDATION.md"
        if not doc_path.is_file():
            pytest.skip("docs/E2E_VALIDATION.md not found")
        content = doc_path.read_text(encoding="utf-8")
        assert "conclave-subset" in content, (
            "E2E_VALIDATION.md must document the conclave-subset CLI"
        )

    def test_e2e_doc_contains_synthesis_step(self) -> None:
        """docs/E2E_VALIDATION.md must document the synthesis API step."""
        doc_path = REPO_ROOT / "docs" / "E2E_VALIDATION.md"
        if not doc_path.is_file():
            pytest.skip("docs/E2E_VALIDATION.md not found")
        content = doc_path.read_text(encoding="utf-8").lower()
        assert "synth" in content, (
            "E2E_VALIDATION.md must document the synthesis step"
        )

    def test_e2e_doc_contains_todo_capture_markers(self) -> None:
        """docs/E2E_VALIDATION.md must contain TODO capture markers for live validation."""
        doc_path = REPO_ROOT / "docs" / "E2E_VALIDATION.md"
        if not doc_path.is_file():
            pytest.skip("docs/E2E_VALIDATION.md not found")
        content = doc_path.read_text(encoding="utf-8")
        assert "TODO" in content, (
            "E2E_VALIDATION.md must contain TODO markers for live validation captures"
        )
